### ISSUE TITLE
Facebook Unity SDK Linking error

### ISSUE THREAD

**Issue by msureka** [facebook/facebook-sdk-for-unity#135]
Hello,

I have added the Facebook Unity SDK, and when I try to run it on Xcode, it gives an error during linking. There are no other 3rd party plugins apart from Facebook.

Undefined symbols for architecture arm64:
  "_ui", referenced from:
      _CanvasFacebook_ui_m4186985473 in Bulk_Facebook.Unity_0.o
     (maybe you meant: __ZN7plcrash5async34plcrash_async_dwarf_read_uintmax64IyEE15plcrash_error_tP21plcrash_async_mobjectPK23plcrash_async_byteordermlhPT_, _Unityplcrash_async_mobject_read_uint32 , _Unityplcrash_async_task_read_uint64 , _plcrash_async_task_read_uint8 , _png_get_uint_32 , _UNITY_png_get_uint_31 , _stbir_resize_uint16_generic , _stbir_resize_uint8_generic , _stbir_resize_uint8 , _UNITY_png_save_uint_16 , _Unityplcrash_async_mobject_read_uint16 , _uintUniformFuncs , _Unityplcrash_async_mobject_read_uint64 , _png_get_uint_16 , _CanvasFacebook_ui_m4186985473 , _plcrash_async_task_read_uint16 , _CanvasScaler_set_uiScaleMode_m1089684310 , _UNITY_png_save_uint_32 , _Unityplcrash_async_mobject_read_uint8 , _Unityplcrash_async_task_read_uint32 , _CanvasScaler_get_uiScaleMode_m424842665 , _stbir_resize_uint8_srgb_edgemode , _stbir_resize_uint8_srgb )
  "_activateApp", referenced from:
      _CanvasFacebook_activateApp_m3886921503 in Bulk_Facebook.Unity_0.o
      _CanvasFacebook_ActivateApp_m946310245 in Bulk_Facebook.Unity_0.o
     (maybe you meant: _CanvasFacebook_activateApp_m3886921503)
  "_initScreenPosition", referenced from:
      _CanvasFacebook_initScreenPosition_m2210395772 in Bulk_Facebook.Unity_0.o
      _CanvasFacebook_Init_m4156905438 in Bulk_Facebook.Unity_0.o
     (maybe you meant: _CanvasFacebook_initScreenPosition_m2210395772)
  "_logPurchase", referenced from:
      _CanvasFacebook_logPurchase_m3032031329 in Bulk_Facebook.Unity_0.o
     (maybe you meant: _CanvasFacebook_logPurchase_m3032031329)
  "_logout", referenced from:
      _CanvasFacebook_logout_m115309677 in Bulk_Facebook.Unity_0.o
      _CanvasFacebook_LogOut_m292792237 in Bulk_Facebook.Unity_0.o
     (maybe you meant: _CanvasFacebook_logout_m115309677)
  "_init", referenced from:
      _CanvasFacebook_init_m1733547387 in Bulk_Facebook.Unity_0.o
     (maybe you meant: _cf2_arrstack_init, _cf2_glyphpath_init , _cf2_stack_init , _cf2_hintmap_init , _vp8_loop_filter_frame_init , _vp8_loop_filter_init , _vp8_init_mbmode_probs , _cf2_initGlobalRegionBuffer , __ZN7plcrash5async33plcrash_async_dwarf_fde_info_initIjEE15plcrash_error_tPNS0_28plcrash_async_dwarf_fde_infoEP21plcrash_async_mobjectPK23plcrash_async_byteordermb , _cff_decoder_init , __ZN7plcrash5async33plcrash_async_dwarf_cie_info_initIjEE15plcrash_error_tPNS0_28plcrash_async_dwarf_cie_infoEP21plcrash_async_mobjectPK23plcrash_async_byteorderPNS0_16gnu_ehptr_readerIT_EEm , _Unityplcrash_async_cfe_reader_init , _FMOD_mdct_init , _FMOD_vorbis_book_init_decode , _UNITY_tt_driver_init , _psh_globals_funcs_init , _cff_driver_init , _cff_face_init , _cff_size_init , _cff_slot_init , __ZNSt3__112basic_stringIcNS_11char_traitsIcEEN3Alg13UserAllocatorIcEEE6__initEPKcm , _UNITY_tt_face_init , __ZN13dynamic_arrayI15DirectAudioInfoLm4EE18resize_initializedEmRKS0_12ResizePolicy , _vpx_codec_dec_init_ver , __ZN13dynamic_arrayIP17ClippedDetailMeshLm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayI11CarveResultLm8EE18resize_initializedEmRKS0_12ResizePolicy , _plframe_cursor_thread_init , _Unityplcrash_async_mobject_init , _FMOD_vorbis_info_init , _FMOD_vorbis_comment_init , _FMOD_vorbis_synthesis_init , _FMOD_ogg_sync_init , _protobuf_c_service_generated_init , _plcrash_nasync_macho_init , _jpeg_mem_init , __ZN9b2Contact13s_initializedE , __ZN13dynamic_arrayIPS_IfLm4EELm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayIN21SimpleMediaAttributes14AudioTrackInfoELm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayIN13VideoPlayback15AudioOutputInfoELm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayIP8MaterialLm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayI16HeightMeshBVNodeLm4EE18resize_initializedEmRKS0_12ResizePolicy , _cf2_hintmask_init , __ZN13dynamic_arrayIN19CompositeCollider2D11SubColliderELm8EE18resize_initializedEmRKS1_12ResizePolicy , _Unityplframe_cursor_init , _Unityplcrash_async_thread_state_mach_thread_init , _plcrash__crash_report__init , _unity_z_tr_init , __ZNSt3__112basic_stringIcNS_11char_traitsIcEEN3Alg13UserAllocatorIcEEE6__initIPcEENS_9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeESA_SA_ , _cf2_initLocalRegionBuffer , _ps_hints_init , _UNITY_tt_size_init , __FMOD_vorbis_window_init , __ZN13dynamic_arrayIPN5physx12PxRigidActorELm8EE18resize_initializedEmRKS2_12ResizePolicy , _Unityplcrash_async_objc_cache_init , __ZN13dynamic_arrayINSt3__14pairI4PPtrI14SphereColliderES4_EELm4EE18resize_initializedEmRKS5_12ResizePolicy , __ZN13dynamic_arrayI4PPtrI15CapsuleColliderELm4EE18resize_initializedEmRKS2_12ResizePolicy , __ZN13dynamic_arrayIN14SerializedFile14SerializedTypeELm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayIbLm1EE18resize_initializedEmRKb12ResizePolicy , _UNITY_png_init_read_transformations , _UNITY_png_init_io , _UNITY_png_info_init_3 , _Unityplcrash_async_file_init , _Unityplcrash_async_thread_state_mcontext_init , _Unityplcrash_log_writer_init , _Unityplcrash_async_symbol_cache_init , _il2cpp_runtime_class_init , _il2cpp_init_utf16 , __ZN13dynamic_arrayIhLm16EE18resize_initializedEmRKh12ResizePolicy , _initialTime , __ZN13dynamic_arrayIcLm1EE18resize_initializedEmRKc12ResizePolicy , __ZN13dynamic_arrayIN2UI8UIVertexELm4EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayI12SpriteVertexLm4EE18resize_initializedEmRKS0_12ResizePolicy , _sfnt_init_face , __ZN13dynamic_arrayIP6ThreadLm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayIP20TaskProcessorWrapperLm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayIN11UnityEngine15CloudWebService14DataErrorEvent15FileErrorDetailELm8EE18resize_initializedEmRKS3_12ResizePolicy , _cf2_blues_init , _t1_hints_funcs_init , __ZN13dynamic_arrayI11ChannelInfoLm4EE18resize_initializedEmRKS0_12ResizePolicy , _Unityplcrash_async_macho_symtab_reader_init , __Z46imageblock_initialize_deriv_from_work_and_origP10imageblocki , _GC_is_initialized , __ZN13dynamic_arrayIP17IAnimationBindingLm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayI20TransformMaskElementLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI12PropertyNameLm4EE18resize_initializedEmRKS0_12ResizePolicy , _GC_init_size_map , _GC_explicit_typing_initialized , _GC_init_explicit_typing , _GC_initiate_gc , _GC_init_headers , _GC_thr_init , _GC_init , _GC_gcj_malloc_initialized , _GC_bl_init , __ZN13dynamic_arrayIN9ShaderLab21SerializedBindChannelELm4EE18resize_initializedEmRKS1_12ResizePolicy , __ZN6il2cpp6icalls8mscorlib6System10Reflection4Emit13ModuleBuilder10basic_initEP29Il2CppReflectionModuleBuilder , _g_il2cpp_is_fully_initialized , __ZN13dynamic_arrayI10CrowdAgentLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayIN16GeometryJobTasks15GeometryJobTaskELm8EE18resize_initializedEmRKS1_12ResizePolicy , _CanvasFacebook_initScreenPosition_m2210395772 , _UnityRuntimeServices_U24static_initializerU24_m2178156047 , __ZN13dynamic_arrayIdLm8EE18resize_initializedEmRKd12ResizePolicy , __ZN13dynamic_arrayIyLm8EE18resize_initializedEmRKy12ResizePolicy , __ZN13dynamic_arrayI10Matrix4x4fLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayIsLm2EE18resize_initializedEmRKs12ResizePolicy , __ZN13dynamic_arrayI10ColorRGBAfLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI11QuaternionfLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI12ImmediatePtrI9TransformELm8EE18resize_initializedEmRKS2_12ResizePolicy , _MNAndroidDialog_init_m1482618399_MetadataUsageId , __ZN13dynamic_arrayIN19CustomRenderTexture14UpdateZoneInfoELm4EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayIPhLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI31EnlightenSystemAtlasInformationLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI7Hash128Lm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI28EnlightenRendererInformationLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayIN4math14float3_storageELm4EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayI4PPtrI9TransformELm4EE18resize_initializedEmRKS2_12ResizePolicy , __ZN13dynamic_arrayI11TangentInfoLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI16SplashScreenLogoLm4EE18resize_initializedEmRKS0_12ResizePolicy , _MNAndroidMessage_init_m1793992270 , __ZN13dynamic_arrayImLm8EE18resize_initializedEmRKm12ResizePolicy , __ZN13dynamic_arrayIfLm16EE18resize_initializedEmRKf12ResizePolicy , __ZN9ASTCCodec17codec_initializedE , __ZN13dynamic_arrayI4PPtrI8MaterialELm4EE18resize_initializedEmRKS2_12ResizePolicy , __ZN13dynamic_arrayI4PPtrI13MonoBehaviourELm4EE18resize_initializedEmRKS2_12ResizePolicy , __ZN13dynamic_arrayI12PPtrKeyframeLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI11KeyframeTplI11QuaternionfELm4EE18resize_initializedEmRKS2_12ResizePolicy , __ZN13dynamic_arrayItLm2EE18resize_initializedEmRKt12ResizePolicy , __ZN13dynamic_arrayI4PPtrI10GameObjectELm4EE18resize_initializedEmRKS2_12ResizePolicy , _il2cpp_init , __ZN13dynamic_arrayI20BoundCurveDeprecatedLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI14OcclusionSceneLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI20SphericalHarmonicsL2Lm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI11TetrahedronLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI8BitFieldLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI4PPtrI15AudioMixerGroupELm4EE18resize_initializedEmRKS2_12ResizePolicy , _GC_initialize_offsets , __ZN13dynamic_arrayI4PPtrI18AudioMixerSnapshotELm4EE18resize_initializedEmRKS2_12ResizePolicy , __ZN13dynamic_arrayI18ScriptingMethodPtrLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI11ColorRGBA32Lm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI8Vector2fLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI10BlendShapeLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI7SubMeshLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI13BoneInfluenceLm16EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayIN20TextRenderingPrivate8FontImpl13CharacterInfoELm4EE18resize_initializedEmRKS2_12ResizePolicy , __ZN13dynamic_arrayI22GenericDynamicVBOChunkLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayIhLm1EE18resize_initializedEmRKh12ResizePolicy , __ZN13dynamic_arrayIN10GameObject13ComponentPairELm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayINSt3__14pairIi12ImmediatePtrIN5Unity9ComponentEEEELm8EE18resize_initializedEmRKS6_12ResizePolicy , _t2_hints_funcs_init , __ZN13dynamic_arrayI14PortConnectionLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI13HeightmapDataLm4EE18resize_initializedEmRKS0_12ResizePolicy , __Z21scripting_object_init18ScriptingObjectPtr , __ZN13dynamic_arrayI4PPtrI15OcclusionPortalELm4EE18resize_initializedEmRKS2_12ResizePolicy , _GC_init_gcj_malloc , _vp8cx_init_de_quantizer , __ZN7plcrash5async56plcrash_async_dwarf_cie_info_initial_instructions_lengthEPNS0_28plcrash_async_dwarf_cie_infoE , __ZN7plcrash5async56plcrash_async_dwarf_cie_info_initial_instructions_offsetEPNS0_28plcrash_async_dwarf_cie_infoE , __ZN13dynamic_arrayI4PPtrI8RendererELm4EE18resize_initializedEmRKS2_12ResizePolicy , __ZN13dynamic_arrayIfLm4EE18resize_initializedEmRKf12ResizePolicy , __ZN13dynamic_arrayI8JobFenceLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayIN11UnityEngine9Animation14GenericBindingELm4EE18resize_initializedEmRKS2_12ResizePolicy , _GC_bl_init_no_interiors , _UNITY_ft_validator_init , _Leaderboard_initialize_m1778841866 , _GC_thr_initialized , _Unityplcrash_async_macho_string_init , __ZN13dynamic_arrayIP15LODGroupManagerLm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayIN27AnimationLayerMixerPlayable15LayerParametersELm8EE18resize_initializedEmRKS1_12ResizePolicy , _plcrash_async_thread_state_init , _MNAndroidRateUsPopUp_init_m2432095501 , _ExecuteEvents_get_initializePotentialDrag_m2227640438 , __ZN13dynamic_arrayI4PPtrI13AnimationClipELm4EE18resize_initializedEmRKS2_12ResizePolicy , __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initIPcEENS_9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeES9_S9_ , _cff_parser_init , __ZN13dynamic_arrayIN8LODGroup11LODRendererELm4EE18resize_initializedEmRKS1_12ResizePolicy , _fmod_tremor_buffer_init , __ZN13dynamic_arrayI8Vector3fLm4EE18resize_initializedEmRKS0_12ResizePolicy , _vp8_mb_init_dequantizer , _Thread_Thread_init_m3428457272 , __ZN13dynamic_arrayIaLm1EE18resize_initializedEmRKa12ResizePolicy , __ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initIPKcEENS_9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeESA_SA_ , __ZN13dynamic_arrayIxLm8EE18resize_initializedEmRKx12ResizePolicy , _MNIOSDialog_init_m3332402645 , __ZN13dynamic_arrayIjLm4EE18resize_initializedEmRKj12ResizePolicy , _WinRTStore_init_m420138384_MetadataUsageId , _UnityRuntimeServices_U24static_initializerU24_m2178156047_MetadataUsageId , _GC_dirty_init , _StackTrace_init_frames_m3304642995 , __ZN13dynamic_arrayI16BlendShapeVertexLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayIPK26opaqueMTAudioProcessingTapLm8EE18resize_initializedEmRKS2_12ResizePolicy , __initCloud , _MobileNativeMessage_init_m3818231395 , __ZN13dynamic_arrayIN15MetalDynamicVBO20MetalDynamicVBOChunkELm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayIS_I8Vector2fLm4EELm8EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayI26EnlightenSystemInformationLm8EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayIiLm4EE18resize_initializedEmRKi12ResizePolicy , __ZN13dynamic_arrayI33EnlightenTerrainChunksInformationLm4EE18resize_initializedEmRKS0_12ResizePolicy , _StackTrace_init_frames_m3304642995_MetadataUsageId , _MobileNativeDialog_init_m894257896_MetadataUsageId , __ZN13dynamic_arrayI5RectTIfELm4EE18resize_initializedEmRKS1_12ResizePolicy , __Z36imageblock_initialize_orig_from_workP10imageblocki , _SslHandshakeHash_initializePad_m4132246594 , __ZN13dynamic_arrayI11KeyframeTplIfELm4EE18resize_initializedEmRKS1_12ResizePolicy , _ExecuteEvents_get_initializePotentialDrag_m2227640438_MetadataUsageId , __ZN13dynamic_arrayI27ParticleSystemEmissionBurstLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayIPK31TransferFunctionScriptingTraitsLm8EE18resize_initializedEmRKS2_12ResizePolicy , _il2cpp_runtime_object_init_exception , _MobileNativeMessage_init_m3818231395_MetadataUsageId , __ZN6il2cpp6icalls8mscorlib6System9Threading6Thread11Thread_initEP12Il2CppThread , _WinRTStore_init_m420138384 , __ZN13dynamic_arrayI8Vector4fLm4EE18resize_initializedEmRKS0_12ResizePolicy , _UNITY_tt_slot_init , _CanvasFacebook_init_m1733547387 , __ZN13dynamic_arrayI10Matrix4x4fLm16EE18resize_initializedEmRKS0_12ResizePolicy , __Z14kpp_initializeiiiiPK10imageblockP6vtype4IfE , _MNAndroidMessage_init_m1793992270_MetadataUsageId , __ZN13dynamic_arrayI4PPtrI11AudioSourceELm4EE18resize_initializedEmRKS2_12ResizePolicy , _plcrash_nasync_image_list_init , __ZN13dynamic_arrayIN23ReflectionProbesContext23ReflectionProbeCubeInfoELm4EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayIN9SubModule14SubEmitterDataELm4EE18resize_initializedEmRKS1_12ResizePolicy , __ZN13dynamic_arrayI13ProbeSetIndexLm8EE18resize_initializedEmRKS0_12ResizePolicy , _GC_mark_init , _FMOD_vorbis_block_init , __ZN13dynamic_arrayI12LightmapDataLm4EE18resize_initializedEmRKS0_12ResizePolicy , __Z36imageblock_initialize_work_from_origP10imageblocki , __ZN13dynamic_arrayI21AnimationClipOverrideLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI4PPtrI6ObjectELm4EE18resize_initializedEmRKS2_12ResizePolicy , _MNAndroidRateUsPopUp_init_m2432095501_MetadataUsageId , __ZN13dynamic_arrayIPN11UnityEngine9Animation23CachedComponentBindingsELm8EE18resize_initializedEmRKS3_12ResizePolicy , __ZN13dynamic_arrayI4AABBLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayIN5Unity5Cloth26ClothConstrainCoefficientsELm4EE18resize_initializedEmRKS2_12ResizePolicy , _MobileNativeDialog_init_m894257896 , __ZN7plcrash5async33plcrash_async_dwarf_fde_info_initIyEE15plcrash_error_tPNS0_28plcrash_async_dwarf_fde_infoEP21plcrash_async_mobjectPK23plcrash_async_byteordermb , _MNAndroidDialog_init_m1482618399 , __ZN7plcrash5async33plcrash_async_dwarf_cie_info_initIyEE15plcrash_error_tPNS0_28plcrash_async_dwarf_cie_infoEP21plcrash_async_mobjectPK23plcrash_async_byteorderPNS0_16gnu_ehptr_readerIT_EEm , _SslHandshakeHash_initializePad_m4132246594_MetadataUsageId , _MNIOSRateUsPopUp_init_m4225995751 , _FMOD_ogg_stream_init , _MNWP8Dialog_init_m1026343343 , _Unityplcrash_async_cfe_entry_init , _HMAC_initializePad_m3828610671 , __ZN13dynamic_arrayI11KeyframeTplI8Vector3fELm4EE18resize_initializedEmRKS2_12ResizePolicy , _MNWP8Message_init_m460883572 , __ZN13dynamic_arrayIN4core12basic_stringIcNS0_20StringStorageDefaultIcEEEELm8EE18resize_initializedEmRKS4_12ResizePolicy , _il2cpp_runtime_object_init , __ZN13dynamic_arrayI19LightProbeOcclusionLm4EE18resize_initializedEmRKS0_12ResizePolicy , __ZN13dynamic_arrayI10MinMaxAABBLm4EE18resize_initializedEmRKS0_12ResizePolicy , _MNIOSMessage_init_m3459693856 , _MNWP8RateUsPopUp_init_m2167163837 , _HMAC_initializePad_m3828610671_MetadataUsageId , __ZN13dynamic_arrayIN21ExecutionOrderManager25DefaultExecutionOrderInfoELm4EE18resize_initializedEmRKS1_12ResizePolicy , _GC_init_parallel )
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can you please check and advice what the issue could be?

Thanks!

**Comment by msureka** [comment]
Update: Getting the same above error even on an empty new project which has only the FacebookSDK. 

Unity 5.6.4.p1
Facebook Unity SDK 7.11.0
XCode 9.2
Building for iOS 10.0 as deployment target

Please advice!

**Comment by CrystalPony** [comment]
I'm having the same issue.
@msureka Please let me know if you manage to fix it.

**Comment by CrystalPony** [comment]
The issue is not present in 7.10.0

**Comment by handcircus** [comment]
Same here - Unity 5.6 linker issues on iOS. Also some binary libraries built without bitcode

**Comment by kobyleha** [comment]
Same problem. Forced to rollback to 7.10.0

**Comment by rusitschka** [comment]
Same here with 2017.2.1f1.

**Comment by enghoff** [comment]
Me too ☹️ 2017.3.0f3

**Comment by CrazyD0G** [comment]
Had same issue while trying building for Android, Unity 2017.3.0.p4

**Comment by kobyle69** [comment]
Same here,

7.11.0 uses iOS library to v4.28.0
It lookes like iOS v4.29.0 fixed some bug the is related:
"Emission of bitcodes for XCode 9 / iOS 11 SDK" (https://developers.facebook.com/docs/ios/change-log-4x)

Can someone compile latest iOS SDK (4.30.0) to Unity?

**Comment by MixMasterRickyC** [comment]
Same here

**Comment by chamnassi2** [comment]
I resolved.

I wrote to
https://developers.facebook.com/bugs/965852950229310/

**Comment by AdnanNazir** [comment]
same issue for me!
using 7.10.1

**Comment by NatashaKSS** [comment]
Same here

**Comment by NatashaKSS** [comment]
Yes I am able to verify that the temporary file provided by @chamnassi2 (much thanks 👍 ) is able to solve the issue.

For those who may want more details about how I did it, you can refer to my notes below!
Unity version: 2017.3.0f3
FacebookSDK version: 7.11.0

1. I removed `Facebook.Unity.dll` from the Facebook SDK package in your Unity project here `FacebookSDK > Plugins > Facebook.Unity.dll`.
2. I pasted the temporary file `Facebook.Unity.dll` linked above by @chamnassi2 [here](https://drive.google.com/open?id=13dJ5lC4OxWOjwra0TWh2qpCryekAw8Jw).
3. Run your Unity project to make sure everything still works. Depending on how you did steps 1 & 2, you might need to update your Facebook App ID again. You may do so by clicking on `Facebook` on your Unity project's toolbar and going to `Edit Settings`.
4. Build your XCode project and open it.
5. Build your project in XCode. Here, for me, I had some errors related to the `Bitcode` setting, so I went to my Build Settings and set `Enable Bitcode` in the section called `Build Options` to "No".
6. You should be able to build now.

**Comment by dilmerv** [comment]
@NatashaKSS thanks for the detailed instructions, I was able to solve it as well using version of Unity 2017.2.0f3.

**Comment by sarebots** [comment]
@chamnassi2 Using your dll significantly reduced the number of errors for me but I'm still left with 1:
```

Undefined symbols for architecture arm64:
  "_FBRewardedVideoAdBridgeOnVideoComplete", referenced from:
      _RewardedVideoAdBridgeIOS_FBRewardedVideoAdBridgeOnVideoComplete_m2350798992 in Bulk_Assembly-CSharp_0.o
      _RewardedVideoAdBridgeIOS_Create_m2690962177 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _RewardedVideoAdBridgeIOS_FBRewardedVideoAdBridgeOnVideoComplete_m2350798992)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
P.S. I'm also using Facebook Audience Network

**Comment by chamnassi2** [comment]
@sarebots hi.
I did not use it.

Like your log, "FBRewardedVideoAdBridgeOnVideoComplete" was not found in the framework.

But I found something else.
"FBRewardedVideoAdBridgeOnComplete" in the framework!!!!!!!!!!!!

You can find the external call in RewardedVideoAd.cs (line 607).

[DllImport ("__Internal")]
         private static extern void FBRewardedVideoAdBridgeOnVideoComplete (int uniqueId,
         FBRewardedVideoAdBridgeExternalCallback callback);

If you change this as below, I think there is a possibility that it will work.
(FBRewardedVideoAdBridgeOnVideoComplete -> FBRewardedVideoAdBridgeOnComplete)

[DllImport ("__Internal")]
         private static extern void FBRewardedVideoAdBridgeOnComplete (int uniqueId,
         FBRewardedVideoAdBridgeExternalCallback callback);

I have not tested it, but I would like to share your test results.
If your test results are successful, the project was not tested enough.

**Comment by sarebots** [comment]
@chamnassi2 
I tried your fix  (FBRewardedVideoAdBridgeOnVideoComplete -> FBRewardedVideoAdBridgeOnComplete) and I'm able to build the app now however it no longer shows rewarded video ads and this is what I'm getting in log:
`
RewardedVideo ad failed to load with error: Error Domain=com.facebook.ads.sdk Code=1001 "No fill" UserInfo={NSLocalizedDescription=No fill, FBAdErrorDetailKey={`

**Comment by chamnassi2** [comment]
@sarebots I'm sorry. I can not help about runtime issue.

**Comment by joaquingrech** [comment]
i'm sorry facebook doesn't release an emergency patch for this. You can't build at all on unity for iOS! Do they even test it? :?

**Comment by maciejorlinski** [comment]
Facebook doesn't give a damn, you're pretty much forced to use their services anyway, so why would they bother with quality assurance?

**Comment by mihailogazda** [comment]
What the hell Facebook... What kind of mokeys are working theree??

**Comment by MikeKellyDatrys** [comment]
painful having to do this; but thanks for the temp file. seems to have broken my fb login code, but at least it deploys.

**Comment by joaquingrech** [comment]
Don't worry guys, it's only 26 days on "open" status. It's not like this is urgent right?

**Comment by rusitschka** [comment]
I got an email from Apple today saying:

"Your  Facebook SDK for iOS is out of date and missing important iOS 11 fixes  that make it easier for people to log into your app. When you upgrade to  the latest SDK, fewer people will have to re-enter their Facebook  username and password to use your app because their logged in state is  maintained in Safari.  On average, we have seen a 14% better log in  success rate on iOS 11 for apps using our latest SDK upgrade."

We're using Unity SDK 7.10.1 because 7.11.0 is broken on iOS - and now this email...

**Comment by mihailogazda** [comment]
We got the same yeah... We are out of date but can't update. 👍

**Comment by hippogamesunity** [comment]
Same here, please fix it! Will try the workaround suggested.

**Comment by lemon-li** [comment]
Please Fix !!!

**Comment by hippogamesunity** [comment]
I can confirm that suggested workaround works fine.

**Comment by mihailogazda** [comment]
They released 7.11.1 hotfix, claiming that it was fixed, trying now...

**Comment by dbuscaglia** [comment]
Any update on this?

**Comment by sarebots** [comment]
It was fixed in 7.11.1 onwards, but I got the same issue in 7.12.1.
Rolled back to 7.12.0, works fine.

**Comment by birdkingz** [comment]
Just every single time, when I'm about to update FB SDK, the latest one will always come with problem!
Luckily @sarebots you stated that this issue is still happening in 7.12.1
Now I have rolled back to 7.12.0.

**Comment by congtk1992** [comment]
back to 7.10.1.
all above error.

**Comment by sshumihin** [comment]
7.12.1 still have the issue.

**Comment by waht123msn** [comment]
back to 7.12.0 works fine.hahhahaa

**Comment by Claytonious** [comment]
Is there any news on a fix for this? We would like to at least get the fixes that removed warnings log spam that were in 7.12.1, but we're stuck on 7.12.0 due to this issue.

**Comment by wo0t7** [comment]
There is a new update that fixes the problem 7.12.2

**Comment by STARasGAMES** [comment]
Unity 2017.4.17f1 
Facebook SDK  7.15.1(latest for now) 7.15.0 and 7.12.2 didn't work for us.

**7.12.0 works fine**

**Comment by KylinChang** [comment]
The issue is the platform of plugin is not setup correctly. I think you can fix that by selecting the correct platform in the inspector. After importing the SDK, You can go to the inspector of **FacebookSDK -> Plugins** and check the platform of each plugin. For example, only select Android for Android plugin and only WebGL for Canvas plugin.

**Comment by dreamade** [comment]
What @KylinChang suggests works. Plugins to change platform: 

Plugins/Android/Facebook.Unity.IOS
Plugins/Canvas -> Change canvas related to WebGL
Plugins/IOS/Facebook.Unity.IOS

It's funny to have Facebook.Unity.IOS dll inside Android folder though. If you dont check it, your build wont work :/
