### ISSUE TITLE
v7.16.1 Android crash on startup

### ISSUE THREAD

**Issue by walaoRIKI** [facebook/facebook-sdk-for-unity#281]
Hi, I getting a crash recently when I working and build on different PC with facebook SDK version 7.15.1 and 7.16.1, version 7.17.1 having some cinemachine error so I didn't use it. I tried to delete and reimport all plugin(Firebase, facebook and google play) but the crash still happening.

Here the error code
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: FATAL EXCEPTION: main
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: Process: com.Spacepup.Archwar, PID: 6556
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at com.facebook.internal.BoltsMeasurementEventListener.open(BoltsMeasurementEventListener.java:54)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at com.facebook.internal.BoltsMeasurementEventListener.getInstance(BoltsMeasurementEventListener.java:70)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:313)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at com.facebook.marketing.internal.MarketingInitProvider.onCreate(MarketingInitProvider.java:42)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at android.app.ActivityThread.installProvider(ActivityThread.java:6414)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at android.app.ActivityThread.installContentProviders(ActivityThread.java:5961)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5867)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at android.app.ActivityThread.access$1100(ActivityThread.java:200)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6692)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.Spacepup.Archwar-l5qr7jBo5nK8NeD1-OHCIw==/base.apk"],nativeLibraryDirectories=[/data/app/com.Spacepup.Archwar-l5qr7jBo5nK8NeD1-OHCIw==/lib/arm, /data/app/com.Spacepup.Archwar-l5qr7jBo5nK8NeD1-OHCIw==/base.apk!/lib/armeabi-v7a, /system/lib]]
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2019/07/11 11:47:55.822 6556 6556 Error AndroidRuntime: ... 17 more

**Comment by max-tu** [comment]
Similar to me, I have tried from v7.16.0 to v7.17.1 Could not build for Android with one of the versions. v7.16.1 built successfully but my game crash at the start running.

**Comment by walaoRIKI** [comment]
@max-tu I fixed the crash issue on my side. My situation is caused by Firebase unity sdk 6.2.x, so I downgraded to 6.1.1 then I fixed the crash on startup issue

**Comment by sotrosh** [comment]
I tried firebase sdk 6.1.1 and facebook sdk 7.16.1 and it still crashes at launch.

**Comment by max-tu** [comment]
Thank you! My problem is goggle ad mobile. I'm testing to fix that.
    On Sunday, 28 July 2019, 04:43:10 GMT+7, Serhii Otroshchenko <notifications@github.com> wrote:  
 
 
I tried firebase sdk 6.1.1 and facebook sdk 7.16.1 and it still crashes at launch.
