### ISSUE TITLE
7.17.2 RejectedExecutionException: Task com.facebook.internal.FetchedAppGateKeepersManager$1@3f2a531 rejected from java.util.concurrent.ThreadPoolExecutor

### ISSUE THREAD

**Issue by seagullua** [facebook/facebook-sdk-for-unity#306]
In the game, we have an uncaught exception from new FB SDK

I think that the FB SDK should try/catch this exception but not throw it down to our application.

Full-stack:
```
java.util.concurrent.RejectedExecutionException: Task com.facebook.internal.FetchedAppGateKeepersManager$1@3f2a531 rejected from java.util.concurrent.ThreadPoolExecutor@1cbc2d2[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 39]
java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
com.facebook.internal.FetchedAppGateKeepersManager.loadAppGateKeepersAsync(FetchedAppGateKeepersManager.java:76)
com.facebook.internal.FetchedAppGateKeepersManager.getGateKeeperForKey(FetchedAppGateKeepersManager.java:146)
com.facebook.appevents.AppEventsLoggerImpl.logEvent(AppEventsLoggerImpl.java:645)
com.facebook.appevents.AppEventsLoggerImpl.logEvent(AppEventsLoggerImpl.java:221)
com.facebook.appevents.AppEventsLogger.logEvent(AppEventsLogger.java:428)
com.facebook.unity.FB.LogAppEvent(FB.java:255)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source)
com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
android.os.MessageQueue.next(MessageQueue.java:392)
android.os.Looper.loop(Looper.java:135)
com.unity3d.player.UnityPlayer$e.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException ()
UnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args)
Facebook.Unity.Mobile.Android.AndroidFacebook.AppEventsLogEvent (System.String logEvent, Nullable`1 valueToSum, System.Collections.Generic.Dictionary`2 parameters)
Facebook.Unity.FB.LogAppEvent (System.String logEvent, Nullable`1 valueToSum, System.Collections.Generic.Dictionary`2 parameters)
```

**Comment by AIGRIND-LLC** [comment]
The same issue is with Android version.

**Comment by KylinChang** [comment]
Hi @seagullua @AIGRIND-LLC , thanks for the report. We will investigate on the issue and let you know if there is any update.

**Comment by KylinChang** [comment]
Hi @seagullua @AIGRIND-LLC , the issue should be fixed in FB Android SDK v5.4.0. You can rebuild the project to get the latest FB Android SDK.

**Comment by FancisLuo** [comment]
We have get this issue recently, then upgrade to facebook-unity-sdk-7.18.0 following this. But still have the chance to get the exception. How should we deal with it?
