### ISSUE TITLE
Cache directory issue - FacebookSdk.getCacheDir causing tons of ANR

### ISSUE THREAD

**Issue by archengineer** [facebook/facebook-sdk-for-unity#318]
Hi,

Yesterday suddenly we started to see tons of ANR in the google play developer console.
All the ANR's common logs show that, FacebookSdk.getCacheDir causing these ANRs. 
Also we saw related issues like this. For example : https://developers.facebook.com/support/bugs/1398287143658627/

On the android sdk, it seems fixed today with commit 'Fix cache directory issue in CrashReport' (https://github.com/facebook/facebook-android-sdk/commit/856665c5e0ede060b3a0f18af8a808aba26d4778).

Can you also update the Unity SDK, so we can update quickly and release the new version because right now, most of our users started to see ANR yesterday even though we uploaded build to play store 1 week ago.

-----------------------------Log Start-----------------------------
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x75c2b468 self=0xefc3c000
  | sysTid=12204 nice=0 cgrp=default sched=0/0 handle=0xf48af4a8
  | state=S schedstat=( 231921051 20218234 456 ) utm=16 stm=7 core=2 HZ=100
  | stack=0xff0fd000-0xff0ff000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait (Native method)
- waiting on <0x032bd1da> (a java.lang.Object)
  at java.lang.Thread.parkFor$ (Thread.java:2137)
- locked <0x032bd1da> (a java.lang.Object)
  at sun.misc.Unsafe.park (Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt (AbstractQueuedSynchronizer.java:868)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1021)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1328)
  at java.util.concurrent.CountDownLatch.await (CountDownLatch.java:232)
  at **com.facebook.internal.LockOnGetVariable.waitOnInit (LockOnGetVariable.java:64)**
  at **com.facebook.internal.LockOnGetVariable.getValue (LockOnGetVariable.java:54)**
  at **com.facebook.FacebookSdk.getCacheDir (FacebookSdk.java:954)**
  at **com.facebook.internal.instrument.InstrumentUtility.getInstrumentReportDir **(InstrumentUtility.java:242)
  at **com.facebook.internal.instrument.InstrumentUtility.listCrashReportFiles **(InstrumentUtility.java:124)
  at com.facebook.internal.instrument.crashreport.CrashHandler.sendCrashReports (CrashHandler.java:101)
  at **com.facebook.internal.instrument.crashreport.CrashHandler.enable (CrashHandler.java:73)**
- locked <0x0c34f60b> (a java.lang.Class<com.facebook.internal.instrument.crashreport.CrashHandler>)
  at **com.facebook.internal.instrument.InstrumentManager.start (InstrumentManager.java:46)**
  at **com.facebook.FacebookSdk.sdkInitialize (FacebookSdk.java:326)**
- locked <0x0d064ce8> (a java.lang.Class<com.facebook.FacebookSdk>)
  at **com.facebook.FacebookSdk.sdkInitialize (FacebookSdk.java:239)**
- locked <0x0d064ce8> (a java.lang.Class<com.facebook.FacebookSdk>)
  at **com.facebook.internal.FacebookInitProvider.onCreate (FacebookInitProvider.java:20)**
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1940)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:1915)
  at android.app.ActivityThread.installProvider (ActivityThread.java:6765)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:6312)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6227)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:237)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1792)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7073)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
-----------------------------Log End-----------------------------

Regards.

**Comment by DenizPiri** [comment]
We seem to be affected by this as well. Update for Unity SDK would be greatly appreciated!

**Comment by CodeMasterYi** [comment]
We seem to be affected by this as well. Update for Unity SDK would be greatly appreciated!

**Comment by CodeMasterYi** [comment]
Is it OK that I built an aar from android-5.5.0 and replace the aar file in the Unity SDK?

**Comment by KylinChang** [comment]
Hi @CodeMasterYi @DenizPiri , the issue comes from FBAndroidSDK v5.4.0 and it should be mitigated in v5.4.0 because the issued feature is now disabled and it's fixed in v5.5.0.

**Comment by btmorgan** [comment]
@KylinChang, we are still seeing a high rate of ANR's being reported in the Google Play console originating from com.facebook.FacebookSdk.getCacheDir (FacebookSdk.java:954).

This would seemingly indicate that the issued feature has not been remotely disabled. Any chance you could provide an update on this or when a new plugin with v5.5.0 of the Android SDK integrated will be released?

**Comment by KylinChang** [comment]
Hey @btmorgan , you don't have to wait for the new release because UnitySDK already added dependency for latest Android SDK. You can just re-export your Android Project and Rebuild the Android project to get the latest v5.5.0.
Code pointer here if you are interested: https://github.com/facebook/facebook-sdk-for-unity/blob/master/UnitySDK/Assets/FacebookSDK/Plugins/Editor/Dependencies.xml

**Comment by archengineer** [comment]
Hi @btmorgan,
As @KylinChang said, you can resolve your dependencies with using "Play Service Resolver" in Unity then you will see android core will update itself to version 5.5.0.
