### ISSUE TITLE
'RegisterMonoModules.h' file not found XCode iOS

### ISSUE THREAD

**Issue by naklow12** [facebook/facebook-sdk-for-unity#323]
I can't build on iOS but I can play on Editor. 

Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityInterface.h:22:10: 'RegisterMonoModules.h' file not found
Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityInterface.mm:19:10: In file included from Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityInterface.mm:19:

This happens only on XCode. It works well on Android. I checked from Facebook developers and I can see my installing there.

**Comment by KylinChang** [comment]
Hi @naklow12 , the issue is related to Unity Editor, which version of Unity Editor are you using? We find that some alpha version of Unity Editor may have this issue.

**Comment by naklow12** [comment]
It is 3.0a8. But I solved by commenting "import RegisterMonoModules.h" on FBUnityInterface.h script. It was not using it. And it solved I got build and tested Facebook Developers it's working. Thanks.

**Comment by ilterbilguven** [comment]
Using Unity 2019.3.0f6 and 2019.3.1f1, and this issue still exists. According to Unity Issue Tracker https://issuetracker.unity3d.com/issues/filenotfoundexception-when-building-a-project-with-facebook-sdk-for-ios , there will be no "RegisterMonoModules.h" anymore. You need to update the SDK.

**Comment by huynguyencong** [comment]
It is still happen to me. Should update SDK to fix it.

**Comment by bakalarczuk** [comment]
SDK update on iOS breaking FB SDK on Android. I suggest SDK developers to better checking what they publishing. Now I've got FB SDK downgraded for Android build, but it doesn't work on iOS build, because of RegisterMonoModules.h... thanks FB...

**Comment by h3902340** [comment]
This bug still exists in FacebookSDK 7.21.2 with Unity 2019.4.9.
