### ISSUE TITLE
Didn't find class "com/facebook/unity/FB"

### ISSUE THREAD

**Issue by aratn0n** [facebook/facebook-sdk-for-unity#327]
I am using version 7.17.2 and enable minify. When I run the game I have this error.

```
E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: Didn't find class "com/facebook/unity/FB" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/aratnon.pixel.idle.dungeon.dunidle-WjCZYh2KLOu_KTK2X9CIYw==/base.apk"],nativeLibraryDirectories=[/data/app/aratnon.pixel.idle.dungeon.dunidle-WjCZYh2KLOu_KTK2X9CIYw==/lib/arm64, /data/app/aratnon.pixel.idle.dungeon.dunidle-WjCZYh2KLOu_KTK2X9CIYw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
    java.lang.ClassNotFoundException: Didn't find class "com/facebook/unity/FB" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/aratnon.pixel.idle.dungeon.dunidle-WjCZYh2KLOu_KTK2X9CIYw==/base.apk"],nativeLibraryDirectories=[/data/app/aratnon.pixel.idle.dungeon.dunidle-WjCZYh2KLOu_KTK2X9CIYw==/lib/arm64, /data/app/aratnon.pixel.idle.dungeon.dunidle-WjCZYh2KLOu_KTK2X9CIYw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
    	at dalvik.system
```
Here is the proguard config that I have.

```
-keep class com.facebook.internal.* {*;}
-keep class com.facebook.* {*;}
```

Do I need to add more rules for the proguard configuration?

**Comment by michael-looply** [comment]
Yeah, the single `*` doesn't act beyond package separators, so `com.facebook.unity.*` is different than `com.facebook.*`.

You can use `**` to match beyond package separators, e.g. `-keep class com.facebook.** { *; }`, or you can add  `-keep class com.facebook.unity.* { *; }`. Note that if you do the latter then you may still run into other `ClassNotFoundException`s.

**Comment by KylinChang** [comment]
The issue should be fixed by modifying your proguard file as @michael-looply mentioned.

**Comment by AnthonyDemanueleFSG** [comment]
I'm still having issues with this one. Can you please check out [this ](https://github.com/facebook/facebook-sdk-for-unity/issues/471)question @KylinChang @michael-looply ?

Cheers.
