### ISSUE TITLE
FB SDK 9: Null Access Token After Init()

### ISSUE THREAD

**Issue by byeates-zynga** [facebook/facebook-sdk-for-unity#521]
## Checklist
* [x]  I've updated to the latest released version of the SDK
* [x]  I've searched for existing [GitHub issues](https://github.com/facebook/facebook-sdk-for-unity/issues)
* [x]  I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
* [x]  I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
* [x]  This issue is not security related and can safely be disclosed publicly on GitHub

## Environment
Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

* Unity Editor Version: `2018.4.14f1`
* Unity SDK Version: `9.0.0`
* Installation Platform & Version: `[iOS]` version `14.4`

## Goals
What do you want to achieve?

- AccessToken.CurrentAccessToken should persist between sessions

## Expected Results
What do you expect to happen?

- User logs into facebook, relaunches app, and is able to skip the SBUserNotificationAlert and authentication process having just logged in through a previous session

## Actual Results
What actually happened? Can you provide a stack trace?

- AccessToken.CurrentAccessToken is null after Init(), requiring the user to login again

## Steps to Reproduce
What are the steps necessary to reproduce this issue?
1. LoginWithReadPermissions
2. Accept the SFUserNotificationAlert for continuing to login with Facebook
3. Once complete, close and relaunch to LoginWithReadPermissions.
4. Note that the SFUserNotificationAlert will appear again, as the FB class AccessToken is null, and the process cannot be avoided

## Code Samples & Details
Please provide a code sample, as well as any additional details, to help us track down the issue. If you can provide a link to a test project that allows us to reproduce the issue, this helps us immensely in both the speed and quality of the fix.

It appears that AccessToken.CurrentAccessToken is null after Init() for a user that has previously just logged in.

I verified that this issue does not appear in SDK 7.1, the AccessToken will be non-null for a user that has just logged in.

I resolved this issue by caching the access token, and reapplying it after FB.Init() is called, but it seems the core fix would involve a fix in the SDK.

**Comment by SeriouslySam** [comment]
We're seeing this issue as well. Unity 2018.4.23 and FB SDK 9.0.0. Happens on both classic login and limited login on iOS 14.5 beta.

Tested it on iOS12 as well and in there it does retain the login between sessions.

**Comment by byeates-zynga** [comment]
> We're seeing this issue as well. Unity 2018.4.23 and FB SDK 9.0.0. Happens on both classic login and limited login on iOS 14.5 beta.
> 
> Tested it on iOS12 as well and in there it does retain the login between sessions.

FWIW, I tested it on 14.4, and the same problem happened there

**Comment by ppansy** [comment]
It's unclear how to reproduce the issue with the steps provided. Please add a sample app to reproduce the issue. Thanks!

**Comment by SeriouslySam** [comment]
@byeates-zynga Do you mind sharing how do you reapply the access token? I'm not sure I understood but wouldn't mind trying if that can be applied also to limited login.

**Comment by SeriouslySam** [comment]
[ios14_login_issue.zip](https://github.com/facebook/facebook-sdk-for-unity/files/5995179/ios14_login_issue.zip)

@ppansy Here's a small repro.

repro steps:
- Add Facebook ID to some project you have access to on the FB settings
- Compile the project (I used XCode 12.5 beta to be able to execute it on iOS 14.5 device)
- App will automatically do init and log the results (see Test.cs). A button is provided to login.
- Our expectation is that the access token is cached in the keychain and once login is done once, then subsequent calls to FB.Init (when starting the app) would also log player in.

This same issue can also be observed by using the Facebook's own demo scene, included in the 9.0.0 Unity SDK.

**Comment by byeates-zynga** [comment]
> @byeates-zynga Do you mind sharing how do you reapply the access token? I'm not sure I understood but wouldn't mind trying if that can be applied also to limited login.

I'm caching the access token in player prefs, and after Init() is finished, I'm setting AccessToken.CurrentAccessToken to the cached value.

**Comment by SeriouslySam** [comment]
We believe we found the root cause for this issue now.  @ppansy 

The access token and authentication token are set to nil in the _invalidateCurrentSession function (https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKAuthenticationStatusUtility.m)

This happens because of a call to https://m.facebook.com/platform/oidc/status?id_token=[accesstoken] which returns a response where "fb-s" header has value "not_authorized". We logged these headers also to be sure that this is the case. This happens to both access token and authentication token.

We further noticed that this only happens on our Test Apps (https://developers.facebook.com/docs/development/build-and-test/test-apps/) which we use for all our testing, but on actual production app this issue does not happen. So at the moment it's not stopping us from releasing but it's hurting our testing a lot and would be good if it can be fixed soon.

**Comment by ppansy** [comment]
This should be fixed now. No SDK updates needed. Thanks!

**Comment by ppansy** [comment]
Will close assuming the issue is resolved. Feel free to reopen if otherwise

**Comment by xAdamQ** [comment]
Still happening to me:
Unity 2021.1.21f1
facebook-unity-sdk-11.0.0
OS Linux Manjaro
