### ISSUE TITLE
SDK 11 with Unity Audience Network 6.4.0 pod resolution fails

### ISSUE THREAD

**Issue by IoannisFMG** [facebook/facebook-sdk-for-unity#559]
## Environment

- Unity Editor Version: 2020.3.2f1
- Unity SDK Version: 11
- Unity FBAudienceNetwork SDK: 6.4.0
- Installation Platform & Version: iOS version >10

## Goals

I'm trying to build our game after upgrading the Unity SDK to 11 and Audience Network Unity SDK to 6.4.0
xCode Version 12.5 (12E262) 
macOS v11.4 (20F71)
cocoapods v 1.10.1

## Expected Results

Pods should resolve successfully.

## Actual Results

The pods are not resolving with the following error:
```
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit/Basics":
  In Podfile:
    FBAudienceNetwork (= 6.4.1) was resolved to 6.4.1, which depends on
      FBSDKCoreKit/Basics (>= 7.0.1)

None of your spec sources contain a spec satisfying the dependency: `FBSDKCoreKit/Basics (>= 7.0.1)`.
```

**Aren't FBSDKCoreKit/Basics and FBSDKCoreKit_Basics the same framework?**

## Steps to Reproduce
Try to resolve the Podfile below.

I have tried 

- pod update
- pod deintegrate && pod repo update && pod install
- Removing the ./cocoapods folder and `sudo gem install cocoapods` again

## Code Samples & Details
The podfile I'm using is the following:
```
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'

use_frameworks! :linkage => :static

def all_deps
#AppsFlyer
    pod 'AppsFlyerFramework', '6.3.1'
#Facebook
    pod 'FBSDKCoreKit_Basics', '~> 11'
    pod 'FBSDKCoreKit', '~> 11'
    pod 'FBSDKLoginKit', '~> 11'
    pod 'FBSDKShareKit', '~> 11'
    pod 'FBSDKGamingServicesKit', '~> 11'
#Firebase
    pod 'Firebase/Analytics', '7.11.0'
    pod 'Firebase/Core', '7.11.0'
    pod 'Firebase/RemoteConfig', '7.11.0'
    pod 'Firebase/Crashlytics', '7.11.0'
    pod 'FirebaseInstanceID', '7.11.0'
#Other
    pod 'OpenSSL-Universal'
    pod 'Protobuf'
#AdMob Mediation
    pod 'Google-Mobile-Ads-SDK'
    pod 'AmazonAd'
    pod 'GoogleMobileAdsMediationMoPub'
    pod 'smaato-ios-sdk/Banner'
    pod 'smaato-ios-sdk-mediation-admob/Banner'
    pod 'smaato-ios-sdk/Interstitial'
    pod 'smaato-ios-sdk-mediation-admob/Interstitial'
    pod 'GoogleMobileAdsMediationAppLovin', '10.1.1.0'
    pod 'GoogleMobileAdsMediationFacebook'
    pod 'GoogleMobileAdsMediationUnity'
    pod 'GoogleMobileAdsMediationTapjoy'
    pod 'GoogleMobileAdsMediationChartboost'
    pod 'GoogleMobileAdsMediationInMobi'
    pod 'GoogleMobileAdsMediationFyber', '7.8.5'

    pod 'FBAudienceNetwork', '6.4.1'
#    pod 'GoogleMobileAdsMediationTestSuite'
end

target 'UnityFramework' do
    all_deps
end

target 'Unity-iPhone' do
    pod 'OpenSSL-Universal'
end

post_install do |installer|
    project = installer.pods_project
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'YES'
            config.build_settings['GCC_ENABLE_OBJC_EXCEPTIONS'] = 'YES'

            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
```

If I remove the entry for the FBAudienceNetwork pod, the podfile resolves, but the resolved FBAudienceNetwork version is 5.3.2 which does not contain  the ‘setAdvertiserTrackingEnabled’ method, making the linker fail (since it's mandatory). 
This is the lock file for that case: 

```
PODS:
  - AmazonAd (3.1.0)
  - AppLovinSDK (10.1.1)
  - AppsFlyerFramework (6.3.1):
    - AppsFlyerFramework/Main (= 6.3.1)
  - AppsFlyerFramework/Main (6.3.1)
  - ChartboostSDK (8.4.1)
  - FBAudienceNetwork (5.3.2)
  - FBSDKCoreKit (11.0.0):
    - FBSDKCoreKit/Core (= 11.0.0)
  - FBSDKCoreKit/Core (11.0.0):
    - FBSDKCoreKit_Basics (~> 11.0.0)
  - FBSDKCoreKit_Basics (11.0.0):
    - FBSDKCoreKit_Basics/Basics (= 11.0.0)
  - FBSDKCoreKit_Basics/Basics (11.0.0)
  - FBSDKGamingServicesKit (11.0.0):
    - FBSDKCoreKit (~> 11.0.0)
    - FBSDKCoreKit_Basics (~> 11.0.0)
  - FBSDKLoginKit (11.0.0):
    - FBSDKLoginKit/Login (= 11.0.0)
  - FBSDKLoginKit/Login (11.0.0):
    - FBSDKCoreKit (~> 11.0.0)
    - FBSDKCoreKit_Basics (~> 11.0.0)
  - FBSDKShareKit (11.0.0):
    - FBSDKShareKit/Share (= 11.0.0)
  - FBSDKShareKit/Share (11.0.0):
    - FBSDKCoreKit (~> 11.0.0)
    - FBSDKCoreKit_Basics (~> 11.0.0)
  - Firebase/Analytics (7.11.0):
    - Firebase/Core
  - Firebase/Core (7.11.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 7.11.0)
  - Firebase/CoreOnly (7.11.0):
    - FirebaseCore (= 7.11.0)
  - Firebase/Crashlytics (7.11.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 7.11.0)
  - Firebase/RemoteConfig (7.11.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 7.11.0)
  - FirebaseABTesting (7.11.0):
    - FirebaseCore (~> 7.0)
  - FirebaseAnalytics (7.11.0):
    - FirebaseAnalytics/AdIdSupport (= 7.11.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30908.0)
  - FirebaseAnalytics/AdIdSupport (7.11.0):
    - FirebaseAnalytics/Base (= 7.11.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleAppMeasurement/AdIdSupport (= 7.11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30908.0)
  - FirebaseAnalytics/Base (7.11.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30908.0)
  - FirebaseCore (7.11.0):
    - FirebaseCoreDiagnostics (~> 7.4)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.11.0):
    - GoogleDataTransport (~> 8.4)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30908.0)
  - FirebaseCrashlytics (7.11.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleDataTransport (~> 8.4)
    - nanopb (~> 2.30908.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstallations (7.11.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (7.11.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
  - FirebaseRemoteConfig (7.11.0):
    - FirebaseABTesting (~> 7.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
  - Fyber_Marketplace_SDK (7.8.5):
    - Fyber_Marketplace_SDK/IASDKCore (= 7.8.5)
    - Fyber_Marketplace_SDK/IASDKMRAID (= 7.8.5)
    - Fyber_Marketplace_SDK/IASDKVideo (= 7.8.5)
  - Fyber_Marketplace_SDK/IASDKCore (7.8.5)
  - Fyber_Marketplace_SDK/IASDKMRAID (7.8.5):
    - Fyber_Marketplace_SDK/IASDKCore
  - Fyber_Marketplace_SDK/IASDKVideo (7.8.5):
    - Fyber_Marketplace_SDK/IASDKCore
  - Google-Mobile-Ads-SDK (8.5.0):
    - GoogleAppMeasurement (< 9.0, >= 7.0)
    - GoogleUserMessagingPlatform (>= 1.1)
  - GoogleAppMeasurement (7.11.0):
    - GoogleAppMeasurement/AdIdSupport (= 7.11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30908.0)
  - GoogleAppMeasurement/AdIdSupport (7.11.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30908.0)
  - GoogleDataTransport (8.4.0):
    - GoogleUtilities/Environment (~> 7.2)
    - nanopb (~> 2.30908.0)
    - PromisesObjC (~> 1.2)
  - GoogleMobileAdsMediationAppLovin (10.1.1.0):
    - AppLovinSDK (= 10.1.1)
    - Google-Mobile-Ads-SDK (>= 8.3.0)
  - GoogleMobileAdsMediationChartboost (8.4.1.1):
    - ChartboostSDK (= 8.4.1)
    - Google-Mobile-Ads-SDK (>= 8.4.0)
  - GoogleMobileAdsMediationFacebook (5.3.2.0):
    - FBAudienceNetwork (= 5.3.2)
    - Google-Mobile-Ads-SDK (>= 7.42.2)
  - GoogleMobileAdsMediationFyber (7.8.5.0):
    - Fyber_Marketplace_SDK (= 7.8.5)
    - Google-Mobile-Ads-SDK (~> 8.0)
  - GoogleMobileAdsMediationInMobi (9.1.7.0):
    - Google-Mobile-Ads-SDK (>= 8.3.0)
    - InMobiSDK/Core (= 9.1.7)
  - GoogleMobileAdsMediationMoPub (5.17.0.0):
    - Google-Mobile-Ads-SDK (~> 8.0)
    - mopub-ios-sdk (= 5.17.0)
  - GoogleMobileAdsMediationTapjoy (12.8.1.0):
    - Google-Mobile-Ads-SDK (~> 8.0)
    - TapjoySDK (= 12.8.1)
  - GoogleMobileAdsMediationUnity (3.7.2.0):
    - Google-Mobile-Ads-SDK (~> 8.0)
    - UnityAds (= 3.7.2)
  - GoogleUserMessagingPlatform (2.0.0)
  - GoogleUtilities/AppDelegateSwizzler (7.4.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.4.1):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (7.4.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.4.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.4.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.4.1)"
  - GoogleUtilities/Reachability (7.4.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.4.1):
    - GoogleUtilities/Logger
  - InMobiSDK/Core (9.1.7)
  - mopub-ios-sdk (5.17.0):
    - mopub-ios-sdk/MoPubSDK (= 5.17.0)
  - mopub-ios-sdk/Core (5.17.0)
  - mopub-ios-sdk/MoPubSDK (5.17.0):
    - mopub-ios-sdk/Core
    - mopub-ios-sdk/NativeAds
  - mopub-ios-sdk/NativeAds (5.17.0):
    - mopub-ios-sdk/Core
  - nanopb (2.30908.0):
    - nanopb/decode (= 2.30908.0)
    - nanopb/encode (= 2.30908.0)
  - nanopb/decode (2.30908.0)
  - nanopb/encode (2.30908.0)
  - OpenSSL-Universal (1.1.1100)
  - PromisesObjC (1.2.12)
  - Protobuf (3.17.0)
  - smaato-ios-sdk-mediation-admob/Banner (8.5.0.1):
    - Google-Mobile-Ads-SDK (~> 8.5.0)
    - smaato-ios-sdk/Banner (>= 21.5.2)
  - smaato-ios-sdk-mediation-admob/Interstitial (8.5.0.1):
    - Google-Mobile-Ads-SDK (~> 8.5.0)
    - smaato-ios-sdk/Interstitial (>= 21.5.2)
  - smaato-ios-sdk/Banner (21.6.14):
    - smaato-ios-sdk/Modules/Banner
    - smaato-ios-sdk/Modules/Core
    - smaato-ios-sdk/Modules/RichMedia
  - smaato-ios-sdk/Interstitial (21.6.14):
    - smaato-ios-sdk/Modules/Interstitial
    - smaato-ios-sdk/Modules/RichMedia
    - smaato-ios-sdk/Modules/Video
  - smaato-ios-sdk/Modules/Banner (21.6.14):
    - smaato-ios-sdk/Modules/Core
  - smaato-ios-sdk/Modules/Core (21.6.14)
  - smaato-ios-sdk/Modules/Interstitial (21.6.14):
    - smaato-ios-sdk/Modules/Core
  - smaato-ios-sdk/Modules/OpenMeasurement (21.6.14):
    - smaato-ios-sdk/Modules/Core
  - smaato-ios-sdk/Modules/RichMedia (21.6.14):
    - smaato-ios-sdk/Modules/Core
    - smaato-ios-sdk/Modules/OpenMeasurement
  - smaato-ios-sdk/Modules/Video (21.6.14):
    - smaato-ios-sdk/Modules/Core
    - smaato-ios-sdk/Modules/OpenMeasurement
  - TapjoySDK (12.8.1)
  - UnityAds (3.7.2)

DEPENDENCIES:
  - AmazonAd
  - AppsFlyerFramework (= 6.3.1)
  - FBSDKCoreKit (~> 11)
  - FBSDKCoreKit_Basics (~> 11)
  - FBSDKGamingServicesKit (~> 11)
  - FBSDKLoginKit (~> 11)
  - FBSDKShareKit (~> 11)
  - Firebase/Analytics (= 7.11.0)
  - Firebase/Core (= 7.11.0)
  - Firebase/Crashlytics (= 7.11.0)
  - Firebase/RemoteConfig (= 7.11.0)
  - FirebaseInstanceID (= 7.11.0)
  - Google-Mobile-Ads-SDK
  - GoogleMobileAdsMediationAppLovin (= 10.1.1.0)
  - GoogleMobileAdsMediationChartboost
  - GoogleMobileAdsMediationFacebook
  - GoogleMobileAdsMediationFyber (= 7.8.5)
  - GoogleMobileAdsMediationInMobi
  - GoogleMobileAdsMediationMoPub
  - GoogleMobileAdsMediationTapjoy
  - GoogleMobileAdsMediationUnity
  - OpenSSL-Universal
  - Protobuf
  - smaato-ios-sdk-mediation-admob/Banner
  - smaato-ios-sdk-mediation-admob/Interstitial
  - smaato-ios-sdk/Banner
  - smaato-ios-sdk/Interstitial

SPEC REPOS:
  trunk:
    - AmazonAd
    - AppLovinSDK
    - AppsFlyerFramework
    - ChartboostSDK
    - FBAudienceNetwork
    - FBSDKCoreKit
    - FBSDKCoreKit_Basics
    - FBSDKGamingServicesKit
    - FBSDKLoginKit
    - FBSDKShareKit
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseRemoteConfig
    - Fyber_Marketplace_SDK
    - Google-Mobile-Ads-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleMobileAdsMediationAppLovin
    - GoogleMobileAdsMediationChartboost
    - GoogleMobileAdsMediationFacebook
    - GoogleMobileAdsMediationFyber
    - GoogleMobileAdsMediationInMobi
    - GoogleMobileAdsMediationMoPub
    - GoogleMobileAdsMediationTapjoy
    - GoogleMobileAdsMediationUnity
    - GoogleUserMessagingPlatform
    - GoogleUtilities
    - InMobiSDK
    - mopub-ios-sdk
    - nanopb
    - OpenSSL-Universal
    - PromisesObjC
    - Protobuf
    - smaato-ios-sdk
    - smaato-ios-sdk-mediation-admob
    - TapjoySDK
    - UnityAds

SPEC CHECKSUMS:
  AmazonAd: 9adf416ea36ca2325ce2040c0cf124f071089904
  AppLovinSDK: 575c3c64158878fdd445ea3d48f4fd2233633336
  AppsFlyerFramework: ea0232bd216ee54622da396479d95ad13d1dd2c3
  ChartboostSDK: 299f9e83cf9c6d6ea8154ace88831a3cb171fce6
  FBAudienceNetwork: f080b871e9b45f6ad67cf6c6e7d681dbe199fb47
  FBSDKCoreKit: 3e6f565de8b4fbe11f8ee5d499f5898b0bde2cdd
  FBSDKCoreKit_Basics: 9cf699662174870962deb39f07a5d70d4594c4b7
  FBSDKGamingServicesKit: eb757c3c9b50758fd20a58d362f2a5d8ab3dcb58
  FBSDKLoginKit: 0ba3e15e9bdbeb46716d0fa375e6b71c39d4c477
  FBSDKShareKit: 0119c74ceddb5ae191c87808c93d2714231cc998
  Firebase: c121feb35e4126c0b355e3313fa9b487d47319fd
  FirebaseABTesting: e66f1f80747792630d9b292966de206d5df9853b
  FirebaseAnalytics: cd3bd84d722a24a8923918af8af8e5236f615d77
  FirebaseCore: 907447d8917a4d3eb0cce2829c5a0ad21d90b432
  FirebaseCoreDiagnostics: 68ad972f99206cef818230f3f3179d52ccfb7f8c
  FirebaseCrashlytics: 272b675aa9d1e9bae1f9e1449fcc1f2cf6042806
  FirebaseInstallations: a58d4f72ec5861840b84df489f2668d970df558a
  FirebaseInstanceID: ad5135045a498d7775903efd39762d2cdfa1be27
  FirebaseRemoteConfig: 0ea30de5fb0231df8c1bdcdf3b6c23bdc5066131
  Fyber_Marketplace_SDK: 432b7044dc466245029dd1fcab84d6bf1693b6d6
  Google-Mobile-Ads-SDK: 6f5c41bf73db1656e5b203ba9c31e3d0899a128d
  GoogleAppMeasurement: fd19169c3034975cb934e865e5667bfdce59df7f
  GoogleDataTransport: cd9db2180fcecd8da1b561aea31e3e56cf834aa7
  GoogleMobileAdsMediationAppLovin: 3e0b8e1867be6eee43ba37cf421ed5ca6291cc23
  GoogleMobileAdsMediationChartboost: 3b12c5325d659caa914ce84a187a908fc2b54ba3
  GoogleMobileAdsMediationFacebook: a79e8cf20016beb9b6707b38d725477717eb6948
  GoogleMobileAdsMediationFyber: 19c630966dffdaf7a454c329da27c4df1bbc9674
  GoogleMobileAdsMediationInMobi: 581cf3b413fa9484cd14031c2060b7b1424fb252
  GoogleMobileAdsMediationMoPub: 5c17c4e8553e1aa46376e08ac3a9f3ccf8f62698
  GoogleMobileAdsMediationTapjoy: f3ccafe3fb7be8114facedc6ba09178f26bd27a7
  GoogleMobileAdsMediationUnity: 09727c4c01043d104443f0455ba8127ad074df67
  GoogleUserMessagingPlatform: ab890ce5f6620f293a21b6bdd82e416a2c73aeca
  GoogleUtilities: f8a43108b38a68eebe8b3540e1f4f2d28843ce20
  InMobiSDK: 4b46bffcc222a894f1550a0d11e2895f4f9c906b
  mopub-ios-sdk: 36d322902674b79b0560a1cb8d15af0548d364ea
  nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
  OpenSSL-Universal: ebc357f1e6bc71fa463ccb2fe676756aff50e88c
  PromisesObjC: 3113f7f76903778cf4a0586bd1ab89329a0b7b97
  Protobuf: 7327d4444215b5f18e560a97f879ff5503c4581c
  smaato-ios-sdk: ef8ac13b2aca1bd9ecf9dc64fde9b21ce3cc2301
  smaato-ios-sdk-mediation-admob: 1c8f37e41c7b07b290696d1adf5f3eccc7fdf5f9
  TapjoySDK: 6d344dfb0cd205014c9286580d5c97857b170402
  UnityAds: cca7e2191591e0bb5d45231f012a2c8722c3e686

PODFILE CHECKSUM: 91cc0bb569b3ca6e341fd3ab9c6485c14680e8af

COCOAPODS: 1.10.1
```

**Comment by eugene-goncharov** [comment]
Same here

**Comment by joesus** [comment]
Issue explanation in https://github.com/facebook/facebook-ios-sdk/issues/1773

**Comment by mgrogin** [comment]
So what versions work well together?

**Comment by mgrogin** [comment]
audience-network-unity-sdk-6.4.0
changing `<iosPod name="FBAudienceNetwork" version="~&gt; 6.4.1" />`
 to  `<iosPod name="FBAudienceNetwork" version="~&gt; 6.5.0" />` in the AudienceNetworkDependencies.xml file seems to work on ios with fb Sdk 9.0.0

**Comment by TheHmmka** [comment]
Same here!

**Comment by joesus** [comment]
AN SDK 6.5.1 has been released and should fix the issue. Thanks!

**Comment by Apoll0** [comment]
> AN SDK 6.5.1 has been released and should fix the issue. Thanks!

Hello!
Where can we download this? There is only 6.4.0 version on the site

**Comment by Eberpraw** [comment]
> 

Hey, only 6.4.1 is available on the website. I still have this issue Dec 22, 2021. Is there any way to fix it myself? It is not possible to downgrade, as Apple will not accept apps running lower than FBSDK 11.0.0.

[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit/Basics":
  In Podfile:
    FBAudienceNetwork (~> 6.4.1) was resolved to 6.4.1, which depends on
      FBSDKCoreKit/Basics (>= 7.0.1)

None of your spec sources contain a spec satisfying the dependency: `FBSDKCoreKit/Basics (>= 7.0.1)`.

**Comment by zakyg** [comment]
How come this was closed a year ago but only AN 6.4 is still available on the site?

**Comment by TeorikDeli** [comment]
Still, no download link for a newer, fixed version. 🤦🏻‍♂️

**Comment by NudeNULL** [comment]
How is this still not fixed? Even the workaround using the older Facebook SDK version is not working anymore

**Comment by mamehiko** [comment]
I'm getting the same error.
but I found the method I want to use in the Facebook SDK.
For example SetAdvertiserTrackingEnabled and SetDataProcessingOptions.
https://github.com/facebook/facebook-sdk-for-unity/blob/a23fe4517a711fc7ea9d4956f4f3d04a11d002d4/Facebook.Unity/Mobile/IMobileFacebook.cs

I decided to use these instead of AudienceNetwork.
1. remove AudienceNetwork
2. install Facebook SDK https://developers.facebook.com/docs/unity
3. replace AudienceNetwork.AdSettings.SetAdvertiserTrackingEnabled with FB.Mobile.SetAdvertiserTrackingEnabled 

Still testing, but hoping it works.

**Comment by sarebots** [comment]
> None of your spec sources contain a spec satisfying the dependency: `FBSDKCoreKit/Basics (>= 7.0.1)`

This worked, except I had to change it to 6.12.0
For future users, you can check the latest iOS version available [here](https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/changelog)

**Comment by daltonbr** [comment]
Changing it to `~> 6.4` will allow you to have a larger range (`>= 6.4` and `< 7.0`).
Still going on for me today with the need to accept `6.15.0`
