### ISSUE TITLE
Facebook v13.2.0 Windows Platform Login Error

### ISSUE THREAD

**Issue by YianChen75** [facebook/facebook-sdk-for-unity#620]
## Checklist

- [V] I've updated to the latest released version of the SDK
- [V] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-sdk-for-unity/issues)
- [V] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [V] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [V] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Unity Editor Version: '2020.3.33f1'
- Unity SDK Version: `13.2.0`
- Installation Platform & Verison: `Windows`

i use facebook sdk 13.2.0 build windows executable run WindowsExample scene
show error message when facebook logging in
Error: ERROR: Failed to start login flow,InnerErrorCode: 190,InnerErrorMessage: Error validating application. Invalid application ID.,InnerErrorSubcode: 0,InnerErrorTraceId: Aky-edNMT0goMPXzyd3NA0I

Facebook EditorSetting -> Facebook App Id And ClientToken fields are entered

How to solve this error ?

**Comment by saxahan** [comment]
You can use this as a workaround solution for iOS example. You can add FacebookClientToken to Info.plist with post process

`private void EditInfoPlist(string path)
        {
            var plistPath = path + "/Info.plist";
            var plist = new PlistDocument();
            plist.ReadFromString(File.ReadAllText(plistPath));

            var rootDict = plist.root;

            // FacebookClientToken
            YLogger.Log($"FacebookClientToken {FacebookSettings.ClientToken}");

            if (!string.IsNullOrEmpty(FacebookSettings.ClientToken))
            {
                rootDict.SetString("FacebookClientToken", FacebookSettings.ClientToken);
            }

            File.WriteAllText(plistPath, plist.WriteToString());
        }`

**Comment by YianChen75** [comment]
Thanks for your reply 

But in this case we need to use facebook login at window platform, we've already initialized facebook sdk but meet this error while trying to login. Is there windowns file which does like Info.plist for iOS?
So we can use FacebookClientToken as reference just like your solution for iOS platform.

> You can use this as a workaround solution for iOS example. You can add FacebookClientToken to Info.plist with post process
> 
> ```
> private void EditInfoPlist(string path)
>         {
>             var plistPath = path + "/Info.plist";
>             var plist = new PlistDocument();
>             plist.ReadFromString(File.ReadAllText(plistPath));
> 
>             var rootDict = plist.root;
> 
>             // FacebookClientToken
>             YLogger.Log($"FacebookClientToken {FacebookSettings.ClientToken}");
> 
>             if (!string.IsNullOrEmpty(FacebookSettings.ClientToken))
>             {
>                 rootDict.SetString("FacebookClientToken", FacebookSettings.ClientToken);
>             }
> 
>             File.WriteAllText(plistPath, plist.WriteToString());
>         }
> ```

**Comment by YianChen75** [comment]
Thanks for your reply 

But in this case we need to use facebook login at window platform, we've already initialized facebook sdk but meet this error while trying to login. Is there windowns file which does like Info.plist for iOS?
So we can use FacebookClientToken as reference just like your solution for iOS platform.

**Comment by YianChen75** [comment]
Thanks for your reply

But in this case we need to use facebook login at window platform, we've already initialized facebook sdk but meet this error while trying to login. Is there windowns file which does like Info.plist for iOS?
So we can use FacebookClientToken as reference just like your solution for iOS platform.

**Comment by saxahan** [comment]
Yes indeed you can take it from **FacebookSettings.ClientToken** and do not forget set the value on inspector before.

**Comment by YianChen75** [comment]
Yep, we can set FacebookClientToken, but the problem is there’s no file is similar to info.plist at our current platform, Windows. That’s why even we set up    FacebookClientToken then it still failed while using Facebook login.
Is there any file at Windows platform can go like info.plist?

**Comment by zenlita** [comment]
Hi, thank you for reporting this issue. We would like to update that we have released v14.0.0 that would address this bug. You may download it at https://developers.facebook.com/docs/unity/downloads. If there are further issues, please report bugs at https://developers.facebook.com/support/bugs/. Thank you!

**Comment by jtigner-sg** [comment]
@zenlita - This is still an issue in the 14.0.0 SDK due to the changes made by @JordiFB in this commit: https://github.com/facebook/facebook-sdk-for-unity/commit/de1244f35efc8f612556394d63bf7b0151ad3e11
this reverted the change made by @JarWarren in this commit:
https://github.com/facebook/facebook-sdk-for-unity/commit/af943730649b8d88b77db021dd51aa327ec2c17f

We still receive the following error when attempting to log into Facebook through the Unity Editor while on a Windows machine.

**Error: FB Login Error: ERROR: Failed to start login flow,InnerErrorCode: 190,InnerErrorMessage: Error validating application. Invalid application ID.,InnerErrorSubcode: 0,InnerErrorTraceId: AASflXc8pT-05wWG3XfpEAk**

Facebook.Unity.CallbackManager:TryCallCallback<Facebook.Unity.ILoginResult> (object,Facebook.Unity.IResult)
Facebook.Unity.CallbackManager:CallCallback (object,Facebook.Unity.IResult)
Facebook.Unity.CallbackManager:OnFacebookResponse (Facebook.Unity.IInternalResult)
Facebook.Unity.Windows.WindowsWrapper/<>c__DisplayClass4_0:<LogInWithScopes>b__1 (fbg.Error)
fbg.Request`1<fbg.AccessToken>:dispatchError (fbg.Message)
fbg.RequestManager:tick ()
fbg.Globals:tick ()
Facebook.Unity.Windows.WindowsWrapper:Tick ()
Facebook.Unity.Windows.WindowsFacebook:Tick ()
Facebook.Unity.Windows.WindowsFacebookGameObject:Update ()

I have attached screenshots that indicate the difference in DLLs that are loaded for SDK 11.0.0 which works with Editor login on Windows and one that displays the 14.0.0 behavior of loading the incorrected DLLs
![image-2022-07-12-10-55-16-537](https://user-images.githubusercontent.com/67081299/178547648-3f611b52-1a39-44ee-b099-44961a59c93f.png)
![image-2022-07-12-11-03-41-990](https://user-images.githubusercontent.com/67081299/178547655-ac915c90-61b7-4f68-bf8f-ddcf12281bf3.png)

**Comment by nehal-git** [comment]
@jtigner-sg issue still persist in 14.1.0 update
