### ISSUE TITLE
14.0.0 SDK still errors when trying to log into SDK through Unity Editor on Windows OS

### ISSUE THREAD

**Issue by jtigner-sg** [facebook/facebook-sdk-for-unity#629]
I have also posted this in Facebook Support: https://developers.facebook.com/support/bugs/733502257901756/

@zenlita - This is still an issue in the 14.0.0 SDK due to the changes made by @JordiFB in this commit: https://github.com/facebook/facebook-sdk-for-unity/commit/de1244f35efc8f612556394d63bf7b0151ad3e11
this reverted the change made by @JarWarren in this commit:
https://github.com/facebook/facebook-sdk-for-unity/commit/af943730649b8d88b77db021dd51aa327ec2c17f

We still receive the following error when attempting to log into Facebook through the Unity Editor while on a Windows machine.

**Error: FB Login Error: ERROR: Failed to start login flow,InnerErrorCode: 190,InnerErrorMessage: Error validating application. Invalid application ID.,InnerErrorSubcode: 0,InnerErrorTraceId: AASflXc8pT-05wWG3XfpEAk**

Facebook.Unity.CallbackManager:TryCallCallback<Facebook.Unity.ILoginResult> (object,Facebook.Unity.IResult)
Facebook.Unity.CallbackManager:CallCallback (object,Facebook.Unity.IResult)
Facebook.Unity.CallbackManager:OnFacebookResponse (Facebook.Unity.IInternalResult)
Facebook.Unity.Windows.WindowsWrapper/<>c__DisplayClass4_0:<LogInWithScopes>b__1 (fbg.Error)
fbg.Request`1<fbg.AccessToken>:dispatchError (fbg.Message)
fbg.RequestManager:tick ()
fbg.Globals:tick ()
Facebook.Unity.Windows.WindowsWrapper:Tick ()
Facebook.Unity.Windows.WindowsFacebook:Tick ()
Facebook.Unity.Windows.WindowsFacebookGameObject:Update ()

I have attached screenshots that indicate the difference in DLLs that are loaded for SDK 11.0.0 which works with Editor login on Windows and one that displays the 14.0.0 behavior of loading the incorrected DLLs
![image-2022-07-12-10-55-16-537](https://user-images.githubusercontent.com/67081299/178547648-3f611b52-1a39-44ee-b099-44961a59c93f.png)
![image-2022-07-12-11-03-41-990](https://user-images.githubusercontent.com/67081299/178547655-ac915c90-61b7-4f68-bf8f-ddcf12281bf3.png)

_Originally posted by @jtigner-sg in https://github.com/facebook/facebook-sdk-for-unity/issues/620#issuecomment-1182001904_

**Comment by jtigner-sg** [comment]
Please note that Unity Editor login works on MacO
<img width="1344" alt="Screen Shot 2022-07-12 at 3 19 18 PM" src="https://user-images.githubusercontent.com/67081299/178781962-bee87ccb-9b5d-410c-b51a-13fb67b90e71.png">
S

**Comment by JamesAiken** [comment]
I saw in their commits that they originally put in a fix for this in Editor on Windows. But then decided to remove the fix. 
Looks like we're waiting for a while.

Alternatively if they could provide better instructions for building the SDK, anyone could then fix it themselves, build the SDK and get back to work.

**Comment by JordiFB** [comment]
@JamesAiken  and @jtigner-sg  We will fix this issue in the next version.

**Comment by JamesAiken** [comment]
@JordiFB Is there a timeline for the next version? I'd like to get the SDK working in the next 2 week period.

**Comment by nehal-git** [comment]
is issue still occuring in 14.1.0 update?

**Comment by JordiFB** [comment]
@nehal-git  This issue has been solved in 14.1.0.

**Comment by nehal-git** [comment]
@JordiFB This issue still occurring in windows example sdk v14.1.0

**Comment by JordiFB** [comment]
@nehal-git Could you try to regenerate the library folder of your project?  Also, Could you attach a screenshot of the console log during play mode? Thank you

**Comment by nehal-git** [comment]
@JordiFB I regenerated the library and logger shows this error 
![Screenshot 2022-09-06 120730](https://user-images.githubusercontent.com/82822318/188564262-6e3e6f2e-2ddd-4645-acd4-688ced59956e.png)

**Comment by JordiFB** [comment]
@JordiFB  Thank you so much. 

The issue seems related to your app configuration.  Are you developing your app for our Cloud Gaming platform or for standalone distribution?

Right now, Windows platform is only available for cloud gaming apps.

**Comment by nehal-git** [comment]
@JordiFB Thanks I re-check the app configuration and found that it is using the wrong client token. Now it is working.
