### ISSUE TITLE
Library not loaded: @rpath/FBAEMKit.framework/FBAEMKit

### ISSUE THREAD

**Issue by utkusaridede** [facebook/facebook-sdk-for-unity#659]
## Checklist

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-sdk-for-unity/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Unity Editor Version: `2020.3.42f1`
- Unity SDK Version: `15.1.0`
- Installation Platform & Verison: `[iOS|Android]` version `15.1.0`

## Goals

I want to upgrade the Facebook SDK from 11.0.0 to 15.1.0.

## Expected Results

I expect the application to run without a crash.

## Actual Results

`2022-12-12 10:58:02.112200+0300 X[2885:960799] [general] Error loading /var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/UnityFramework (140):  dlopen(/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/FBAEMKit.framework/FBAEMKit
  Referenced from: <9BADC43E-9E20-3632-B97D-D01CF81F4F4D> /private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/preboot/Cryptexes/OS@rpath/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/System/Library/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache)
2022-12-12 10:58:02.144931+0300 X[2885:960799] [general] Error loading /var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/UnityFramework (140):  dlopen(/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/FBAEMKit.framework/FBAEMKit
  Referenced from: <9BADC43E-9E20-3632-B97D-D01CF81F4F4D> /private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/preboot/Cryptexes/OS@rpath/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/UnityFramework.framework/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/private/var/containers/Bundle/Application/69D00D39-D41D-4E4B-B51A-BD2E4D7F88DD/X.app/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2), '/System/Library/Frameworks/FBAEMKit.framework/FBAEMKit' (errno=2, not in dyld cache)`

## Steps to Reproduce

- Add OneSignal SDK 3.0.7.
- Add Firebase SDK 10.2.0 which requires enabling iOS Resolver Setting - "Add use_frameworks! to Podfile"
- Add Facebook SDK 15.1.0 which states "Add use_frameworks! to Podfile" should not be added as far as I understand.
- Build and run on the real device. An immediate crash will happen.

## Code Samples & Details

A code sample isn't required to reproduce the issue.

It seems that the required Facebook and other frameworks are not included in the Unity-iPhone General "Frameworks, Libraries, and Embedded Content" section if the mentioned use_frameworks! is included in the podfile.

**Comment by go3k** [comment]
I have the same issue, anyone resolved this?

**Comment by utkusaridede** [comment]
> I have the same issue, anyone resolved this? ---Edit Fixed this issue by revert SDK version to 14.1.0

Reverting to the Facebook SDK 11.0.0 fixes, too. Using the most recent version has a problem.

**Comment by SilkageNet** [comment]
Don't you even test it on the real machine when the release comes out?

**Comment by plotlessplot** [comment]
Same issue here. Building with Unity 2021.3.16f1 and Facebook SDK 15.1.0. Immediate crash when attempting to run the application on an iOS device. 

Rolling back to 14.1.0 which had no issues (apart from the need to manually specify the Android SDK path in the Unity editor). 

Hoping for better-tested versions of the SDK down the line. 🤞

**Comment by cmcpasserby** [comment]
it seems to relate to this issue in the facebook-ios-sdk
https://github.com/facebook/facebook-ios-sdk/issues/2128

i can make the latest version run fine if i make those suggested `Podfile` updates, then running `pod install`.

still wish they would properly test there stuff.

**Comment by plotlessplot** [comment]
I was not able to fix it by removing ":linkage => :static", because the Firebase SDK seems to rely on it.

However, I noticed that with FB Unity SDK 14.1.0, the generated Podfile had...

```
use_frameworks! :linkage => :static 
use_frameworks!
```

...at the end, whereas with 15.1.0 there was only...

```
use_frameworks! :linkage => :static
```

I changed my Podfile to the following and it worked correctly. The game loads and seems to work correctly. I'm unsure if this can create issues with other SDKs, though.

```
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'UnityFramework' do
  pod 'AppLovinMediationByteDanceAdapter', '4.8.1.0.1'
  pod 'AppLovinMediationFacebookAdapter', '6.12.0.1'
  pod 'AppLovinMediationFyberAdapter', '8.1.7.1'
  pod 'AppLovinMediationGoogleAdapter', '9.14.0.1'
  pod 'AppLovinMediationGoogleAdManagerAdapter', '9.14.0.1'
  pod 'AppLovinMediationUnityAdsAdapter', '4.4.1.0'
  pod 'AppLovinSDK', '11.6.0'
  pod 'FBSDKCoreKit', '~> 15.1'
  pod 'FBSDKCoreKit_Basics', '~> 15.1'
  pod 'FBSDKGamingServicesKit', '~> 15.1'
  pod 'FBSDKLoginKit', '~> 15.1'
  pod 'FBSDKShareKit', '~> 15.1'
  pod 'Firebase/Analytics', '10.3.0'
  pod 'Firebase/Core', '10.3.0'
  pod 'Firebase/Crashlytics', '10.3.0'
  pod 'Firebase/DynamicLinks', '10.3.0'
  pod 'Firebase/Messaging', '10.3.0'
  pod 'Firebase/RemoteConfig', '10.3.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
use_frameworks!
```

**Comment by cmcpasserby** [comment]
so for me i just had 1 `use_frameworks!` at the end of the file, and one after the
`target 'UnityFramework' do` line

**Comment by unf0rgettable** [comment]
> Мне не удалось исправить это, удалив ":linkage => :static", потому что Firebase SDK, похоже, полагается на это.
> 
> Однако я заметил, что с FB Unity SDK 14.1.0 сгенерированный подфайл...
> 
> ```
> use_frameworks! :linkage => :static 
> use_frameworks!
> ```
> 
> ... в конце, тогда как с 15.1.0 было только...
> 
> ```
> use_frameworks! :linkage => :static
> ```
> 
> Я изменил свой Podfile на следующий, и он работал правильно. Игра загружается и работает без проблем. Однако я не уверен, что это может создать проблемы с другими SDK.
> 
> ```
> source 'https://cdn.cocoapods.org/'
> 
> platform :ios, '12.0'
> 
> target 'UnityFramework' do
>   pod 'AppLovinMediationByteDanceAdapter', '4.8.1.0.1'
>   pod 'AppLovinMediationFacebookAdapter', '6.12.0.1'
>   pod 'AppLovinMediationFyberAdapter', '8.1.7.1'
>   pod 'AppLovinMediationGoogleAdapter', '9.14.0.1'
>   pod 'AppLovinMediationGoogleAdManagerAdapter', '9.14.0.1'
>   pod 'AppLovinMediationUnityAdsAdapter', '4.4.1.0'
>   pod 'AppLovinSDK', '11.6.0'
>   pod 'FBSDKCoreKit', '~> 15.1'
>   pod 'FBSDKCoreKit_Basics', '~> 15.1'
>   pod 'FBSDKGamingServicesKit', '~> 15.1'
>   pod 'FBSDKLoginKit', '~> 15.1'
>   pod 'FBSDKShareKit', '~> 15.1'
>   pod 'Firebase/Analytics', '10.3.0'
>   pod 'Firebase/Core', '10.3.0'
>   pod 'Firebase/Crashlytics', '10.3.0'
>   pod 'Firebase/DynamicLinks', '10.3.0'
>   pod 'Firebase/Messaging', '10.3.0'
>   pod 'Firebase/RemoteConfig', '10.3.0'
> end
> target 'Unity-iPhone' do
> end
> use_frameworks! :linkage => :static
> use_frameworks!
> ```

for me it didn't work

**Comment by unf0rgettable** [comment]
```
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

target 'UnityFramework' do
  pod 'AppLovinMediationAdColonyAdapter', '4.9.0.0.2'
  pod 'AppLovinMediationByteDanceAdapter', '4.8.1.0.1'
  pod 'AppLovinMediationFacebookAdapter', '6.12.0.1'
  pod 'AppLovinMediationGoogleAdapter', '9.14.0.1'
  pod 'AppLovinMediationGoogleAdManagerAdapter', '9.14.0.1'
  pod 'AppLovinMediationIronSourceAdapter', '7.2.6.0.1'
  pod 'AppLovinMediationMintegralAdapter', '7.2.8.0.1'
  pod 'AppLovinMediationUnityAdsAdapter', '4.5.0.0'
  pod 'AppLovinMediationVungleAdapter', '6.12.1.1'
  pod 'AppLovinSDK', '11.6.0'
use_frameworks!
  pod 'FBSDKCoreKit', '~> 15.1'
  pod 'FBSDKCoreKit_Basics', '~> 15.1'
  pod 'FBSDKGamingServicesKit', '~> 15.1'
  pod 'FBSDKLoginKit', '~> 15.1'
  pod 'FBSDKShareKit', '~> 15.1'
  pod 'Firebase/Analytics', '10.1.0'
  pod 'Firebase/Auth', '10.1.0'
  pod 'Firebase/Core', '10.1.0'
  pod 'Firebase/Crashlytics', '10.1.0'
  pod 'Firebase/Storage', '10.1.0'
end
target 'Unity-iPhone' do
end
use_frameworks!
```

this podfile configuration and
`pod install`
**WORKS!**

**Comment by kritikosabzorba** [comment]
We had the same issue. Using XCode 14.1.0 seems to fix the problem.

**Comment by KiranJodhani** [comment]
I had same issue.. Had to revert FB SDK

**Comment by Bogdan-sybo** [comment]
The `use_frameworks!` line was removed in the last(15.1.0) FB SDK version at [this](https://github.com/facebook/facebook-sdk-for-unity/commit/453b5dc330e25ec6e590849df1729bf0e11b8f70) commit.

Adding the line back fixed the issue only for some of our build machines. 
We can see that the error occurs when the `pod install` command doesn't find the `FBSDKCoreKit` framework. Below a comparison of a `pod install` for 2 build nodes. 
![image](https://user-images.githubusercontent.com/62887407/211593470-47b1efe7-6aba-493e-affb-e39e0bf9490d.png)

For some reason those 2 FB frameworks are not added as embeded and this will cause crash on play. This doesn't occur with 14.1.0 SDK version...

**Comment by iremguner** [comment]
> ```
> source 'https://cdn.cocoapods.org/'
> platform :ios, '12.0'
> 
> target 'UnityFramework' do
>   pod 'AppLovinMediationAdColonyAdapter', '4.9.0.0.2'
>   pod 'AppLovinMediationByteDanceAdapter', '4.8.1.0.1'
>   pod 'AppLovinMediationFacebookAdapter', '6.12.0.1'
>   pod 'AppLovinMediationGoogleAdapter', '9.14.0.1'
>   pod 'AppLovinMediationGoogleAdManagerAdapter', '9.14.0.1'
>   pod 'AppLovinMediationIronSourceAdapter', '7.2.6.0.1'
>   pod 'AppLovinMediationMintegralAdapter', '7.2.8.0.1'
>   pod 'AppLovinMediationUnityAdsAdapter', '4.5.0.0'
>   pod 'AppLovinMediationVungleAdapter', '6.12.1.1'
>   pod 'AppLovinSDK', '11.6.0'
> use_frameworks!
>   pod 'FBSDKCoreKit', '~> 15.1'
>   pod 'FBSDKCoreKit_Basics', '~> 15.1'
>   pod 'FBSDKGamingServicesKit', '~> 15.1'
>   pod 'FBSDKLoginKit', '~> 15.1'
>   pod 'FBSDKShareKit', '~> 15.1'
>   pod 'Firebase/Analytics', '10.1.0'
>   pod 'Firebase/Auth', '10.1.0'
>   pod 'Firebase/Core', '10.1.0'
>   pod 'Firebase/Crashlytics', '10.1.0'
>   pod 'Firebase/Storage', '10.1.0'
> end
> target 'Unity-iPhone' do
> end
> use_frameworks!
> ```
> 
> this podfile configuration and `pod install` **WORKS!**

these steps worked for me too. Using XCode 14.2 and Facebook SDK 15.1

**Comment by oliverebert** [comment]
In order to modify the generated Podfile directly in Unity you can create a script like this:

`using System.IO;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;

public class PodFilePostProcess : MonoBehaviour
{
#if UNITY_IOS
    [PostProcessBuildAttribute(45)]//must be between 40 and 50 to ensure that it's not overriden by Podfile generation (40) and that it's added before "pod install" (50)
    private static void PostProcessBuild_iOS(BuildTarget target, string buildPath)
    {
        if (target == BuildTarget.iOS)
        {

            using (StreamWriter sw = File.AppendText(buildPath + "/Podfile"))
            {
                sw.WriteLine("use_frameworks!");
            }
        }
    }
#endif
}`

**Comment by josealvarez97** [comment]
> In order to modify the generated Podfile directly in Unity you can create a script like this:
> 
> ```
> using System.IO;
> using UnityEditor;
> using UnityEditor.Callbacks;
> using UnityEngine;
> 
> public class PodFilePostProcess : MonoBehaviour
> {
> #if UNITY_IOS
>     [PostProcessBuildAttribute(45)]//must be between 40 and 50 to ensure that it's not overriden by Podfile generation (40) and that it's added before "pod install" (50)
>     private static void PostProcessBuild_iOS(BuildTarget target, string buildPath)
>     {
>         if (target == BuildTarget.iOS)
>         {
> 
>             using (StreamWriter sw = File.AppendText(buildPath + "/Podfile"))
>             {
>                 sw.WriteLine("use_frameworks!");
>             }
>         }
>     }
> #endif
> }
> ```

I am using version 15 and this script allowed my app to launch again on my device (was crashing at launch).

**Comment by josealvarez97** [comment]
> > In order to modify the generated Podfile directly in Unity you can create a script like this:
> > ```
> > using System.IO;
> > using UnityEditor;
> > using UnityEditor.Callbacks;
> > using UnityEngine;
> > 
> > public class PodFilePostProcess : MonoBehaviour
> > {
> > #if UNITY_IOS
> >     [PostProcessBuildAttribute(45)]//must be between 40 and 50 to ensure that it's not overriden by Podfile generation (40) and that it's added before "pod install" (50)
> >     private static void PostProcessBuild_iOS(BuildTarget target, string buildPath)
> >     {
> >         if (target == BuildTarget.iOS)
> >         {
> > 
> >             using (StreamWriter sw = File.AppendText(buildPath + "/Podfile"))
> >             {
> >                 sw.WriteLine("use_frameworks!");
> >             }
> >         }
> >     }
> > #endif
> > }
> > ```
> 
> I am using version 15 and this script allowed my app to launch again on my device (was crashing at launch).
> 
> P.S. One issue though, I believe it shouldn't be a monobehaviour. This scripts generally go on the editor folder in Assets, and hence there's no need to inherit from monobehaviour. In fact, (I think) Unity cannot build the project if you attach it to a monobehaviour.

I had issues with my production version. It started crashing again. I am using Unity Cloud build, not sure if there is an issue with that. My development version was working fine on my Mac with my development certificate, but once I uploaded the production version to TestFlight (and App Store in fact), my app was crashing at launch. That was very unfortunate because it happened in production, of course.

Really bothered by this issue.

**Comment by saxahan** [comment]
Same here. Downgraded though

**Comment by JordiFB** [comment]
Hi, sorry to hear about this issue. We are looking into it to fix in the next version. 

Just a couple of questions:
  *  Which cocoapods version are you using?
   * Could you try to use cocoapods 1.11.3 ?

We recommended cocoapods 1.11.3 for UnitySDK 15.1.0  -> Upgrade guide: https://developers.facebook.com/docs/unity/upgrading-7.x

Thank you

**Comment by artMacBookPro** [comment]
> 
Hi!
---
pod --version      
1.11.3
UnitySDK 15.1.0
---

Problem exist!
Dear FB Team, it seems that EVERY last versions of SDK i upgraded (..->14.0, 15.1) was not ready for production and crashed. You definetely should do something with QA process, kmon...

**Comment by artMacBookPro** [comment]
Hi! @JordiFB 
---
pod --version      
1.11.3
UnitySDK 15.1.0
---

Problem exist!
Dear FB Team, it seems that EVERY last versions of SDK i upgraded (..->14.0, 15.1) was not ready for production and crashed. You definetely should do something with QA process, kmon...

**Comment by ahmetyazir22** [comment]
Same issue here, too. "use_frameworks!" is not a viable solution. Please fix.

**Comment by stzjunoh** [comment]
1. Download the Facebook SDK.
2. Delete the "Required device capabilities" entry in the info.plist file inside all Facebook Frameworks.

**Comment by Schrodinger123** [comment]
Revert Facebook SDK to 14.1.0 fix the problem.
FFS FB, hire some QA.

**Comment by JordiFB** [comment]
@artMacBookPro  Could you try the latest version 16.0.0?
Check the upgrade guide before https://developers.facebook.com/docs/unity/upgrading-7.x

**Comment by Apoll0** [comment]
> Could you try the latest version 16.0.0?

Tried today. The problem exists
FB SDK 16.0.0
Unity 2020.3.45
Xcode 14.2

**Comment by JordiFB** [comment]
Thanks @Apoll0  for testing it. 
We will continue working on it.

**Comment by Apoll0** [comment]
Also if you deselect “link frameworks statically” in external dependency manager everything works as expected WBR3 марта 2023 г., в 14:53, JordiFB ***@***.***> написал(а):﻿
Thanks @Apoll0  for testing it.
We will continue working on it.

**Comment by gollobo** [comment]
Any news on this?

**Comment by andymads** [comment]
Same experience for me after updating 14.1.0 to 16.0.0, in 2 projects so far.
Unity 2021.3.21
Xcode 14.2
Cocoapods 1.12.0

Haven't tried any of the workarounds so far.

**Comment by DmitrySharov** [comment]
A week has already been spent on establishing the work of ios because of fb sdk. How is this possible?

The assembly takes place in Unity Cloud.
Accurately reproduced in such combinations:

Unity 2022.2.14f or 2021.3.23f1 (LTS)
Xcode - 1.14.1
Fb sdk 16.0.0

**Comment by AlexisFerrerYsocorp** [comment]
I'm seriously thinking about staying with the 14.1.0 until it's fixed.
Are there any key features or optimizations in the version 15.1.0 or 16.0.0 worth the permanent workaround ?

**Comment by felixkrautschuk** [comment]
I can confirm that upgrading Cocoapods (in my case from 1.11.3) to 1.12.1 solves the crash for me.

**Comment by JordiFB** [comment]
@felixkrautschuk  and @Idomo  Thanks for adding this new information. 

@DmitrySharov  We will continue working to find a solution.

**Comment by reezoobose** [comment]
The only solution is to add them in Framework section .
<img width="676" alt="Screenshot 2023-05-04 at 7 28 04 AM" src="https://user-images.githubusercontent.com/16963195/236094126-150c0bb6-e796-456b-96a6-d8efbac31fc3.png">
Those xcframework files  are available inside pod .
<img width="285" alt="Screenshot 2023-05-04 at 7 31 18 AM" src="https://user-images.githubusercontent.com/16963195/236094675-b47d7350-be6d-4f36-b463-86d4b84b7b68.png">
Just drag the item one after another inside the framework section
Make a build , run the app the crash will be resolved .

**Comment by Overlordshor** [comment]
> JordiFB

Maybe there is a post-processing script that will help close the problem?

**Comment by ulysserus** [comment]
I have fixed the problem by aligning FBSDK podfile versions with unity plugin version (it was basically a clean re-import of the plugin) 

- Unity 2020.3.40f1
- FBSDK 14.1
- Unity version handler all settings to default.


In unity:
<img width="265" alt="image" src="https://github.com/facebook/facebook-sdk-for-unity/assets/115694895/aa28746e-5719-4b79-aad3-d3ce06452c21">


In podfile:
```
source 'https://cdn.cocoapods.org/'
platform :ios, '14.0'
target 'UnityFramework' do
  pod 'AppLovinSDK', '11.9.0'
  pod 'FBSDKCoreKit', '~> 14.1'
  pod 'FBSDKCoreKit_Basics', '~> 14.1'
  pod 'FBSDKGamingServicesKit', '~> 14.1'
  pod 'FBSDKLoginKit', '~> 14.1'
  pod 'FBSDKShareKit', '~> 14.1'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
use_frameworks!
```

**Comment by Davidnovarro** [comment]
> I can confirm that upgrading Cocoapods (in my case from 1.11.3) to 1.12.1 solves the crash for me.

I can confirm the opposite, crash still happens even with Cocoapods 1.12.1

**Comment by JordiFB** [comment]
@Davidnovarro  Could you test the steps from @ulysserus? A clean re=import of the UnitySDK. Also, Are you using Unity SDK 14.1.0 or 16.0.0? Thank you so much.

**Comment by Davidnovarro** [comment]
> @Davidnovarro Could you test the steps from @ulysserus? A clean re=import of the UnitySDK. Also, Are you using Unity SDK 14.1.0 or 16.0.0? Thank you so much.

I've tried clean reimport, it does not work when there are other plugins (Admob SDK), I haven't tried with 14.1. Seems like FB SDK does not work with Cocoapods when there are other libs that are linked statically.

I found a workaround. I removed Cocoapods dependencies from Dependency.xml file, and I have to add Facebook iOS SDK each time through Xcode. Tedious process to be honest.

**Comment by snappedToGrid** [comment]
Thank you @reezoobose , your solution was the only thing that worked for me AND kept Firebase analytics still working.
In the other solutions, if I removed ":linkage => :static" the game did run, but the drawback was that Firebase Analytics stopped working, with your solution it keeps on working.

It's really unfortunate that we need to resort to these kind of workarounds and the SDK can't just work.

**Comment by ihcy-hub** [comment]
> 唯一的解决方案是将它们添加到框架部分。 这些 xcframework 文件在 pod 中可用。 只需将项目依次拖入框架部分 进行构建，运行应用程序即可解决崩溃问题。 <img alt="屏幕截图 2023-05-04 7 28 04 AM" width="676" src="https://user-images.githubusercontent.com/16963195/236094126-150c0bb6-e796-456b-96a6-d8efbac31fc3.png"> <img alt="屏幕截图 2023-05-04 7 31 18 AM" width="285" src="https://user-images.githubusercontent.com/16963195/236094675-b47d7350-be6d-4f36-b463-86d4b84b7b68.png">

Hello, I used your method to build and run successfully, but it cannot be uploaded to appstore

**Comment by YSOStudio** [comment]
Still having the issue with the newly released SDK 16.0.1
https://developers.facebook.com/docs/unity/change-log

**Comment by AlexisFerrerYsocorp** [comment]
Still having the issue with the latest version 16.0.1
https://developers.facebook.com/docs/unity/change-log

**Comment by wristshot0** [comment]
It's frustrating to have to scroll to the bottom of every one of these threads through a bunch of thumbs ups from people who clearly haven't tested across situations, but @reezoobose 's solution works, and is clearly the answer to the problem described by Xcode (that the frameworks are simply not included). Other solutions interfere with other SDKs, including Google's SDK, which is a nonstarter for most projects.

This seems to have become an issue again after the latest Xcode update (14.3.1). Facebook, you need to come out with SDK updates in a timely fashion--as soon as Xcode updates you should be testing your SDK with the new version.

**Comment by grayby** [comment]
Works fine on Facebook SDK 16.0.1 after updating CocoaPods to 1.12.1 and writing 'use_frameworks!' to the end of the Podfile via script
XCode 14.3.1
Unity 2021.3.18

To update pods run in the terminal next commands:

- sudo gem install cocoapods
- pod setup

Check CocoaPods version
pod --version

Hope you will save a few hours and drink some beer instead

**Comment by SaariTech** [comment]
Anyone know how to solve this in Unity Cloud Build? It seems like the issue is at Facebook's side as the other plugins using CocoPods works correctly.

**Comment by AvivWhalo** [comment]
@SaariTech having the same issue with UCB. any idea? should I just downgrade FB SDK?

**Comment by cmcpasserby** [comment]
So @reezoobose post got me onto the right track, since he was adding the xcframeworks to the main `Unity-iPhone` project and not just UnityFramework where things were already added properly.

Simply editing the `Assets/FacebookSDK/Plugins/Editor/Dependencies.xml` file to have `addToAllTargets="true"` added to each line fixes the issues for me, and does not require me manually fixing stuff in xcode after the unity generates the project and `pod install` is called.

After the modifications here is what my `Dependencies.xml` looks like
```xml
<?xml version="1.0" encoding="utf-8"?>
<dependencies>
    <androidPackages>
        <androidPackage spec="com.parse.bolts:bolts-android:1.4.0" />
        <androidPackage spec="com.facebook.android:facebook-core:[16.0,17)" />
        <androidPackage spec="com.facebook.android:facebook-applinks:[16.0,17)" />
        <androidPackage spec="com.facebook.android:facebook-login:[16.0,17)" />
        <androidPackage spec="com.facebook.android:facebook-share:[16.0,17)" />
        <androidPackage spec="com.facebook.android:facebook-gamingservices:[16.0,17)" />
    </androidPackages>
    <iosPods>
        <iosPod name="FBSDKCoreKit_Basics" version="~> 16.0" addToAllTargets="true" />
        <iosPod name="FBSDKCoreKit" version="~> 16.0" addToAllTargets="true" />
        <iosPod name="FBSDKLoginKit" version="~> 16.0" addToAllTargets="true" />
        <iosPod name="FBSDKShareKit" version="~> 16.0" addToAllTargets="true" />
        <iosPod name="FBSDKGamingServicesKit" version="~> 16.0" addToAllTargets="true" />
    </iosPods>
</dependencies>
```

**Comment by wristshot0** [comment]
> So @reezoobose post got me onto the right track, since he was adding the xcframeworks to the main `Unity-iPhone` project and not just UnityFramework where things were already added properly.
> 
> Simply editing the `Assets/FacebookSDK/Plugins/Editor/Dependencies.xml` file to have `addToAllTargets="true"` added to each line fixes the issues for me, and does not require me manually fixing stuff in xcode after the unity generates the project and `pod install` is called.
> 
> After the modifications here is what my `Dependencies.xml` looks like
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <dependencies>
>     <androidPackages>
>         <androidPackage spec="com.parse.bolts:bolts-android:1.4.0" />
>         <androidPackage spec="com.facebook.android:facebook-core:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-applinks:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-login:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-share:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-gamingservices:[16.0,17)" />
>     </androidPackages>
>     <iosPods>
>         <iosPod name="FBSDKCoreKit_Basics" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKCoreKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKLoginKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKShareKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKGamingServicesKit" version="~> 16.0" addToAllTargets="true" />
>     </iosPods>
> </dependencies>
> ```

This makes sense. I haven't tried this as @reezoobose 's solution worked for me, but if it just does what @reezoobose mentioned above then it should work.

I'm really struggling with why this wasn't picked up by Facebook QA--why is this flag false, and why do we have to do this manually?

**Comment by cmcpasserby** [comment]
@wristshot0 well pretty big issues have made it in before, so not all that surprised. I am going to make a PR tonight or tomorrow for this change. But at least for now if people manually do this in their unity projects, its better then having to re do the changes every time you make a new ios build.

**Comment by AvivWhalo** [comment]
> So @reezoobose post got me onto the right track, since he was adding the xcframeworks to the main `Unity-iPhone` project and not just UnityFramework where things were already added properly.
> 
> Simply editing the `Assets/FacebookSDK/Plugins/Editor/Dependencies.xml` file to have `addToAllTargets="true"` added to each line fixes the issues for me, and does not require me manually fixing stuff in xcode after the unity generates the project and `pod install` is called.
> 
> After the modifications here is what my `Dependencies.xml` looks like
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <dependencies>
>     <androidPackages>
>         <androidPackage spec="com.parse.bolts:bolts-android:1.4.0" />
>         <androidPackage spec="com.facebook.android:facebook-core:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-applinks:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-login:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-share:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-gamingservices:[16.0,17)" />
>     </androidPackages>
>     <iosPods>
>         <iosPod name="FBSDKCoreKit_Basics" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKCoreKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKLoginKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKShareKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKGamingServicesKit" version="~> 16.0" addToAllTargets="true" />
>     </iosPods>
> </dependencies>
> ```

Seems to have worked 👏

**Comment by utkusaridede** [comment]
**Environment Update**
- Unity Editor Version: 2022.3.6f1
- Unity SDK Version: 16.1.0
- Xcode Version: 14.3.1
- Cocoapods Version: 1.12.1
- Firebase SDK Version: 11.3.0 (Added to refer to the last paragraph)

None of the solutions worked for me. Therefore I downgraded the version to _14.1.0_ only with the event system fix from _16.1.0_. Additionally, adding missing frameworks to the .xcworkspace project can be automated but I do not want to interfere pre-build process that much while there is time until 14.1.0 reach the end of life.

Unchecking _**Link frameworks statically**_ option in _**iOS Resolver Settings**_ may fix some projects. On the other hand, Firebase and some other SDKs need frameworks to be statically linked.

I'm going to check the subsequent releases.

**Comment by tbiz5270** [comment]
I encountered this problem after integrating the Facebook SDK, which didn't seem to play nicely with the AppLovin MAX SDK settings. 

A mixture of the above solutions worked for me. I'll list the details below.

Unity Editor: 2021.3.25f1
AppLovin MAX Plugin (Unity): 5.11.2
AppLovin MAX Plugin (iOS): 11.11.2
Facebook SDK: 16.0.1
Xcode Version: 14.2

First, I changed my iOS Resolver settings to the following:

<img width="413" alt="iosResolver" src="https://github.com/facebook/facebook-sdk-for-unity/assets/142559054/ddc11e55-832a-4bad-950c-142904c88629">

These settings are different from what AppLovin's integration instructions recommend, but it was the only way I managed to get things working.

My FacebookSDK > Plugins > Editor > Dependencies.xml file looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<dependencies>
    <androidPackages>
        <androidPackage spec="com.parse.bolts:bolts-android:1.4.0" />
        <androidPackage spec="com.facebook.android:facebook-core:[16.0,17)" />
        <androidPackage spec="com.facebook.android:facebook-applinks:[16.0,17)" />
        <androidPackage spec="com.facebook.android:facebook-login:[16.0,17)" />
        <androidPackage spec="com.facebook.android:facebook-share:[16.0,17)" />
        <androidPackage spec="com.facebook.android:facebook-gamingservices:[16.0,17)" />
    </androidPackages>
    <iosPods>
        <iosPod name="FBSDKCoreKit_Basics" version="~> 16.0" />
        <iosPod name="FBSDKCoreKit" version="~> 16.0" />
        <iosPod name="FBSDKLoginKit" version="~> 16.0" />
        <iosPod name="FBSDKShareKit" version="~> 16.0" />
        <iosPod name="FBSDKGamingServicesKit" version="~> 16.0" />
    </iosPods>
</dependencies>
```

After building the project to iOS, it generates a Podfile looking like this:

```
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

target 'UnityFramework' do
  pod 'AppLovinMediationAdColonyAdapter', '4.9.0.0.4'
  pod 'AppLovinMediationByteDanceAdapter', '5.4.0.7.0'
  pod 'AppLovinMediationChartboostAdapter', '9.4.0.0'
  pod 'AppLovinMediationFacebookAdapter', '6.14.0.0'
  pod 'AppLovinMediationGoogleAdapter', '10.9.0.1'
  pod 'AppLovinMediationIronSourceAdapter', '7.4.0.0.1'
  pod 'AppLovinMediationUnityAdsAdapter', '4.8.0.1'
  pod 'AppLovinMediationVungleAdapter', '7.0.1.0'
  pod 'AppLovinSDK', '11.11.2'
  pod 'FBAudienceNetwork', '~> 6.4.1'
  pod 'FBSDKCoreKit', '~> 16.0'
  pod 'FBSDKCoreKit_Basics', '~> 16.0'
  pod 'FBSDKGamingServicesKit', '~> 16.0'
  pod 'FBSDKLoginKit', '~> 16.0'
  pod 'FBSDKShareKit', '~> 16.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
```

However, I had to manually remove the `pod 'FBAudienceNetwork', '~> 6.4.1'` line to make Xcode happy. So my final Podfile looks like this:

```
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

target 'UnityFramework' do
  pod 'AppLovinMediationAdColonyAdapter', '4.9.0.0.4'
  pod 'AppLovinMediationByteDanceAdapter', '5.4.0.7.0'
  pod 'AppLovinMediationChartboostAdapter', '9.4.0.0'
  pod 'AppLovinMediationFacebookAdapter', '6.14.0.0'
  pod 'AppLovinMediationGoogleAdapter', '10.9.0.1'
  pod 'AppLovinMediationIronSourceAdapter', '7.4.0.0.1'
  pod 'AppLovinMediationUnityAdsAdapter', '4.8.0.1'
  pod 'AppLovinMediationVungleAdapter', '7.0.1.0'
  pod 'AppLovinSDK', '11.11.2'
  pod 'FBSDKCoreKit', '~> 16.0'
  pod 'FBSDKCoreKit_Basics', '~> 16.0'
  pod 'FBSDKGamingServicesKit', '~> 16.0'
  pod 'FBSDKLoginKit', '~> 16.0'
  pod 'FBSDKShareKit', '~> 16.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
```

Changing: `'FBAudienceNetwork', '~> 6.4.1'` to `'FBAudienceNetwork', '~> 6.14.0'` to match the AppLovin Facebook Adaptor version also worked. Either way, these changes seem to correctly generate the required pod.

After making these changes to the Podfile, I run `pod update` to install the pods and generate the workspace file.

Open the workspace file (Unity-iPhone.xcworkspace), not the Xcode file (Unity-iPhone.xcodeproj) to open the project in Xcode.

Next, I had to manually drag and drop the Facebook SDK pod frameworks into the Unity-iPhone project:

<img width="512" alt="dragPods" src="https://github.com/facebook/facebook-sdk-for-unity/assets/142559054/06925555-35f4-4890-ad02-8b0ea2af1fc8">

Finally, after all of these steps, I was able to compile the build and run it on my iOS device without crashing on start.

Hope this helps!

**Comment by Schrodinger123** [comment]
OMFG, it's 16.0.1 and this still not fix yet?
Unbelievable META.

**Comment by dreamcodestudio** [comment]
attribute `addToAllTargets="true"` works fine, can you add it by default or present static librarirs for working normal with other SDKs
```xml
<iosPods>
        <iosPod name="FBSDKCoreKit_Basics" version="~> 16.0" />
        <iosPod name="FBSDKCoreKit" version="~> 16.0" />
        <iosPod name="FBSDKLoginKit" version="~> 16.0" />
        <iosPod name="FBSDKShareKit" version="~> 16.0" />
        <iosPod name="FBSDKGamingServicesKit" version="~> 16.0" />
    </iosPods>
```

**Comment by AlexisFerrerYsocorp** [comment]
Still not working with version 16.0.2.
Sadly it's not even a joke...

**Comment by dreamcodestudio** [comment]
In our case updating to 16.0.2 works fine

**Comment by ValeriyBogorodskiy** [comment]
Came across this thread after updating Facebook SDK from 14.1.0 to 16.0.2. Updating pods to the latest version (1.13.0) fixed the issue

**Comment by ankit-infinitygames** [comment]
It's almost 1 year and this issue is still not fixed.

**Comment by mofish9** [comment]
It's unbelievable and this issue still exists on the latest version in 2023.

FB SDK 16.0.2
Firebase SDK 11.6.0
Unity 2021.3.25
Xcode 15.0.1

Do you guys do any testing before the release? The SDKs and Xcode we use are all the latest version and before the FB sdk is introduced, everything works fine.

**Comment by st21a1** [comment]
The problem still exists.
FB SDK 16.0.2
GoogleMobileAds SDK 8.5.2
Unity 2021.3.25
Xcode 14.3.1

**Comment by r0llac0de** [comment]
The problem still exists.
FB SDK 16.0.1
Unity 2022.3.19f1
Xcode 14.3.1

**Comment by crawfordbowl** [comment]
> So @reezoobose post got me onto the right track, since he was adding the xcframeworks to the main `Unity-iPhone` project and not just UnityFramework where things were already added properly.
> 
> Simply editing the `Assets/FacebookSDK/Plugins/Editor/Dependencies.xml` file to have `addToAllTargets="true"` added to each line fixes the issues for me, and does not require me manually fixing stuff in xcode after the unity generates the project and `pod install` is called.
> 
> After the modifications here is what my `Dependencies.xml` looks like
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <dependencies>
>     <androidPackages>
>         <androidPackage spec="com.parse.bolts:bolts-android:1.4.0" />
>         <androidPackage spec="com.facebook.android:facebook-core:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-applinks:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-login:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-share:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-gamingservices:[16.0,17)" />
>     </androidPackages>
>     <iosPods>
>         <iosPod name="FBSDKCoreKit_Basics" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKCoreKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKLoginKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKShareKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKGamingServicesKit" version="~> 16.0" addToAllTargets="true" />
>     </iosPods>
> </dependencies>
> ```

This is fixed the issue for us.

What our auto generated podfile looks like:

```
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'UnityFramework' do
  pod 'AppsFlyerFramework', '6.9.1'
  pod 'FBSDKCoreKit', '~> 16.0.1'
  pod 'FBSDKCoreKit_Basics', '~> 16.0.1'
  pod 'FBSDKGamingServicesKit', '~> 16.0.1'
  pod 'FBSDKLoginKit', '~> 16.0.1'
  pod 'FBSDKShareKit', '~> 16.0.1'
  pod 'FCUUID'
  pod 'Firebase/Analytics', '10.13.0'
  pod 'Firebase/AppCheck', '10.13.0'
  pod 'Firebase/Auth', '10.13.0'
  pod 'Firebase/Core', '10.13.0'
  pod 'Firebase/Crashlytics', '10.13.0'
  pod 'Firebase/Firestore', '10.13.0'
  pod 'Firebase/Messaging', '10.13.0'
end
target 'Unity-iPhone' do
  pod 'FBSDKCoreKit', '~> 16.0.1'
  pod 'FBSDKCoreKit_Basics', '~> 16.0.1'
  pod 'FBSDKGamingServicesKit', '~> 16.0.1'
  pod 'FBSDKLoginKit', '~> 16.0.1'
  pod 'FBSDKShareKit', '~> 16.0.1'
end
use_frameworks! :linkage => :static
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
```

**Comment by RaidelRoss** [comment]
When I do what is suggested in this thread, when I try to validate the app in Xcode it fails.

![image](https://github.com/facebook/facebook-sdk-for-unity/assets/36287019/5328cddd-5648-4932-a331-844c2f5f8a97)

 The only way it works fine is by manually passing the 6 libraries to the

![image](https://github.com/facebook/facebook-sdk-for-unity/assets/36287019/197637ec-677c-440f-aa8a-448a98640862)

Is there any way to automate this?

**Comment by Duloinc** [comment]
The game crashes with the same error, using FB 16.3.1 & cocoapods.

This fixed it for me

target 'UnityFramework' do
  **use_frameworks!**
  pod 'AppsFlyerFramework', '6.13.0'
  pod 'FBSDKCoreKit' 
  pod 'FBSDKCoreKit_Basics'
  pod 'FBSDKGamingServicesKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Core', '10.20.0'
  pod 'Firebase/Messaging', '10.20.0'
  pod 'IronSourceAdMobAdapter', '4.3.52.0'
  pod 'IronSourceSDK', '7.8.0.0'
  pod 'IronSourceUnityAdsAdapter', '4.3.35.0'
end
target 'Unity-iPhone' do
end
**use_frameworks!**

**AND  POD UPDATE**

**Comment by cosgunhalil** [comment]
The app crashed upon startup with the same error when using FBSDK 16.0.2 and CocoaPods 1.15.2. We downgraded FBSDK from 16.0.2 to 14.0.0, which resolved the issue. Now, the app is playable successfully.

**Comment by MuhammedResulBilkil** [comment]
> So @reezoobose post got me onto the right track, since he was adding the xcframeworks to the main `Unity-iPhone` project and not just UnityFramework where things were already added properly.
> 
> Simply editing the `Assets/FacebookSDK/Plugins/Editor/Dependencies.xml` file to have `addToAllTargets="true"` added to each line fixes the issues for me, and does not require me manually fixing stuff in xcode after the unity generates the project and `pod install` is called.
> 
> After the modifications here is what my `Dependencies.xml` looks like
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <dependencies>
>     <androidPackages>
>         <androidPackage spec="com.parse.bolts:bolts-android:1.4.0" />
>         <androidPackage spec="com.facebook.android:facebook-core:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-applinks:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-login:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-share:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-gamingservices:[16.0,17)" />
>     </androidPackages>
>     <iosPods>
>         <iosPod name="FBSDKCoreKit_Basics" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKCoreKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKLoginKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKShareKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKGamingServicesKit" version="~> 16.0" addToAllTargets="true" />
>     </iosPods>
> </dependencies>
> ```

Somehow the app started to not work. Giving this upper error on the XCode. Then I add these to the Dependencies file. It worked. 

Sometimes I just wonder if some perries do something to my code and intentionally make it not work!

**Comment by xmx77** [comment]
After like 3 years still facebook developer they don't test their tools and they always send for us email "threat" with new legal and rules and we must update our products immediately. where ever for me in my next projects i will remove Facebook SDKs completely , Then after few year there is some company make study why facebook disappeared and This is one of the reasons, And for my clients i will charge 5000 USD for any one ask me to add  Facebook SDK , even if the game cost 1$, just to keep clients not use your services. "DON'T FORGET WE HELP FACEBOOK TO COLLECT THE DATA".

What we want : WE WANT Magic SDK one click and everything is add without spend days to solve your problems .


@MuhammedResulBilkil & @cmcpasserby   : Thank you, your solution solved my issue , i just i add "addToAllTargets="true"

**Comment by femoreti** [comment]
> So @reezoobose post got me onto the right track, since he was adding the xcframeworks to the main `Unity-iPhone` project and not just UnityFramework where things were already added properly.
> 
> Simply editing the `Assets/FacebookSDK/Plugins/Editor/Dependencies.xml` file to have `addToAllTargets="true"` added to each line fixes the issues for me, and does not require me manually fixing stuff in xcode after the unity generates the project and `pod install` is called.
> 
> After the modifications here is what my `Dependencies.xml` looks like
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <dependencies>
>     <androidPackages>
>         <androidPackage spec="com.parse.bolts:bolts-android:1.4.0" />
>         <androidPackage spec="com.facebook.android:facebook-core:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-applinks:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-login:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-share:[16.0,17)" />
>         <androidPackage spec="com.facebook.android:facebook-gamingservices:[16.0,17)" />
>     </androidPackages>
>     <iosPods>
>         <iosPod name="FBSDKCoreKit_Basics" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKCoreKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKLoginKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKShareKit" version="~> 16.0" addToAllTargets="true" />
>         <iosPod name="FBSDKGamingServicesKit" version="~> 16.0" addToAllTargets="true" />
>     </iosPods>
> </dependencies>
> ```

Thank you!

**Comment by LaCreArthur** [comment]
adding `addToAllTargets` fixes the iOS build on SDK version 18.0.0 for me
